-- ============================================================================
-- 긴급대응 지원시설 표 신설 + 무장애여행 편의정보 원문 보존 (v1.6.0, 2026-09-08)
--
-- 1) poi_tour_bf_facility.detail_raw
--    한국관광공사 무장애여행 편의정보를 Y/N 플래그로만 저장해 왔다. 서술 원문이
--    남지 않아 ①플래그 규칙이 잘못됐을 때 재파싱이 불가능하고 ②"본관 옆 부스"
--    같은 위치 설명을 안내에 쓸 수 없으며 ③다른 소스와 값이 다를 때 근거를 댈 수
--    없었다. 응답 원문을 그대로 담는다.
--
-- 2) poi_emergency_support
--    전동 보장구 이용자의 이동 중 고장·방전 대응 자원(수리센터·충전기·콜택시 등)을
--    한 표로 모은다. 운영시간(open_hours)을 별도 컬럼으로 두는 이유는, 수리센터가
--    주간에만 운영해 야간에는 위치 정보만으로는 쓸모가 없기 때문이다.
--    confidence 는 출처 신뢰도다. 정식 원천은 'H', 다른 데이터의 비고란에서 얻은
--    단서는 'L' 로 두어 확인 대상임을 표시한다.
--
-- 모두 IF NOT EXISTS 라 재실행해도 안전하다.
-- ============================================================================

BEGIN;

-- 1) 무장애여행 편의정보 원문 보존 -------------------------------------------
ALTER TABLE public.poi_tour_bf_facility
    ADD COLUMN IF NOT EXISTS detail_raw jsonb NULL;

COMMENT ON COLUMN public.poi_tour_bf_facility.detail_raw
    IS '무장애여행 편의정보 응답 원문(JSON). 플래그 재파싱·안내 문구·소스 대조 근거';

-- 2) 긴급대응 지원시설 -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.poi_emergency_support (
	support_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL ,
	support_type varchar(20) NOT NULL ,             -- repair(보장구 수리) / charge(전동보장구 충전) / calltaxi(장애인콜택시)
	sido_code varchar(10) NULL ,                    -- 내부 시도 코드
	sgg_name varchar(60) NULL ,                     -- 시군구명
	name varchar(200) NOT NULL ,                    -- 기관·장소명
	addr_road varchar(600) NULL ,                   -- 도로명 주소
	addr_jibun varchar(600) NULL ,                  -- 지번 주소
	zip_code varchar(10) NULL ,                     -- 우편번호
	latitude double precision NULL ,                -- 위도(WGS84)
	longitude double precision NULL ,               -- 경도(WGS84)
	tel varchar(40) NULL ,                          -- 연락처
	homepage varchar(400) NULL ,                    -- 홈페이지
	open_hours varchar(200) NULL ,                  -- 운영시간 — 야간 대응 가능 여부 판단에 필수
	note varchar(1000) NULL ,                       -- 비고(원문 유지)
	source varchar(40) NULL ,                       -- 출처 코드 (ext_sys_code 또는 수기 표기)
	confidence bpchar(1) DEFAULT 'H' NULL ,         -- H(정식 원천) / L(비고란 유래 — 확인 대상)
	base_dt date NULL ,                             -- 데이터 기준 일자
	del_yn bpchar(1) DEFAULT 'N' NULL ,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL ,
	deleted_at timestamptz NULL ,
	created_by varchar(40) NOT NULL ,
	updated_by varchar(40) NULL ,
	deleted_by varchar(40) NULL ,
	CONSTRAINT pkey_poi_emergency_support PRIMARY KEY (support_id)
);

COMMENT ON TABLE public.poi_emergency_support IS '긴급대응 지원시설 — 보장구 수리·충전·콜택시 등';

CREATE UNIQUE INDEX IF NOT EXISTS uidx_poi_emergency_support_key
    ON public.poi_emergency_support USING btree (support_type, name, coalesce(addr_road, ''));
CREATE INDEX IF NOT EXISTS idx_poi_emergency_support_location
    ON public.poi_emergency_support USING btree (latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_poi_emergency_support_type
    ON public.poi_emergency_support USING btree (support_type);

-- 3) 외부 연동 시스템 코드 ---------------------------------------------------
INSERT INTO public.sys_common_code
    (grp_id, grp_nm, code_id, code_nm, parent_grp_id, parent_code_id, code_type, code_lvl,
     sort_order, use_yn, del_yn, code_des, memo, created_at, created_by)
SELECT 'ext_sys_code', '외부 연동 시스템 코드', 'GG_ASSIST_REPAIR', '경기데이터드림 보조기기 수리 서비스센터',
       null, null, 'S', 1, 8, 'Y', 'N',
       '시군별 보조기기 수리 서비스센터 현황 (poi_emergency_support, support_type=repair)', '',
       CURRENT_TIMESTAMP, 'SYS-MANUAL'
WHERE NOT EXISTS (
    SELECT 1 FROM public.sys_common_code WHERE grp_id = 'ext_sys_code' AND code_id = 'GG_ASSIST_REPAIR'
);

COMMIT;
