-- =====================================================================
--  iitp_db : 비정형(이미지) 수집 데이터셋 스키마
--  SW#2 DataCollector 가 수집/정제한 장애인 고용·교육·행사 및
--  무장애 관광 비정형 이미지 데이터셋을 적재하기 위한 테이블.
--
--  설계 메모
--   - 수집 1건(게시물/관광지) = 1 dis_unst_collect_item
--   - 그 안의 이미지 N장        = N dis_unst_collect_img (item FK)
--   - 파이프라인 단계별 컬럼 매핑:
--       collect_list  -> item(+img.img_url, download_yn='N')
--       downloader    -> img.local_path / file_ext / download_yn / download_err
--       dedup         -> img.md5_hash / sha256_hash / dup_yn / dup_of_img_id
--       label_assist  -> item.inferred_category / domain / match_confidence / needs_review
--       split_manifest-> img.dataset_split / split_seed
--   - 외부 출처 코드(ext_sys) 는 "ext_sys_code" 공통코드 참조.
-- =====================================================================

-- ---------------------------------------------------------------------
--  공통코드: 비정형 수집 외부 출처(ext_sys_code) 추가
--  (sys_common_code 구조는 basic 스키마 참조. 운영 환경에 맞게 조정)
-- ---------------------------------------------------------------------
-- INSERT 예시는 Required_data_insert 스크립트에 두는 것을 권장:
--   ('ext_sys_code','TOUR_BF_API','한국관광공사 무장애여행 OpenAPI', ...)
--   ('ext_sys_code','ABLEJOB',    '장애인잡(나라HR) 게시판/DB',      ...)
--   ('ext_sys_code','WEB_CRAWL',  '외부 공개 사이트 크롤링',          ...)

-- ---------------------------------------------------------------------
--  public.dis_unst_collect_item  (비정형 수집 항목)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.dis_unst_collect_img;
DROP TABLE IF EXISTS public.dis_unst_collect_item;

CREATE TABLE public.dis_unst_collect_item (
    item_id           int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- 고유 식별자
    ext_sys           VARCHAR(20)  NOT NULL,                   -- 수집 외부 출처 코드, "ext_sys_code" comm code 참조 (TOUR_BF_API/ABLEJOB/WEB_CRAWL)
    src_no            VARCHAR(100) NOT NULL,                   -- 출처 게시물/항목 식별번호 (수집 CSV 의 No, 연속 순번 아님)
    src_type          VARCHAR(60),                             -- 출처 원문 분류 (수집 CSV 의 Type, 예: 행사/교육)
    title             VARCHAR(1000) NOT NULL,                  -- 게시물/항목 제목 원문 (수집 CSV 의 Title)
    src_url           VARCHAR(1000),                           -- 출처 상세 페이지/항목 URL (있을 때)

    inferred_category VARCHAR(60),                             -- label_assist 정규화 카테고리 (예: 일자리/채용, 무장애 관광지)
    domain            VARCHAR(20),                             -- 도메인 (고용/문화관광/기타)
    match_confidence  NUMERIC(3,2),                            -- 분류 신뢰도 0.00~1.00
    needs_review      CHAR(1) DEFAULT 'N',                     -- 사람 검토 필요 여부(Y/N)

    collected_at      TIMESTAMPTZ,                             -- 수집(크롤/호출) 시각

    del_yn            bpchar(1) DEFAULT 'N'::bpchar NULL,      -- 삭제 여부: N(정상), Y(삭제)
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,   -- 등록일시
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,   -- 수정일시
    deleted_at        TIMESTAMPTZ NULL,                        -- 삭제 일시 (논리 삭제 시 기록)
    created_by        varchar(40) NOT NULL,                    -- 데이터 생성자, "sys_work_type" comm code 참조 (SYS-BACH/SYS-MANUAL/...)
    updated_by        varchar(40) NULL,                        -- 데이터 수정자
    deleted_by        varchar(40) NULL,                        -- 삭제 처리자

    CONSTRAINT pkey_dis_unst_collect_item PRIMARY KEY (item_id),
    CONSTRAINT uq_dis_unst_collect_item_src UNIQUE (ext_sys, src_no)   -- 같은 출처의 동일 항목 중복 적재 방지
);
CREATE INDEX idx_dis_unst_collect_item_cat  ON public.dis_unst_collect_item USING btree (inferred_category);
CREATE INDEX idx_dis_unst_collect_item_dom  ON public.dis_unst_collect_item USING btree (domain);
CREATE INDEX idx_dis_unst_collect_item_sys  ON public.dis_unst_collect_item USING btree (ext_sys);

COMMENT ON TABLE public.dis_unst_collect_item IS 'SW#2 비정형(이미지) 수집 항목 - 게시물/관광지 단위';
COMMENT ON COLUMN public.dis_unst_collect_item.item_id IS '고유 식별자';
COMMENT ON COLUMN public.dis_unst_collect_item.ext_sys IS '수집 외부 출처 코드, "ext_sys_code" comm code 참조';
COMMENT ON COLUMN public.dis_unst_collect_item.src_no IS '출처 게시물/항목 식별번호 (수집 CSV No)';
COMMENT ON COLUMN public.dis_unst_collect_item.src_type IS '출처 원문 분류 (수집 CSV Type)';
COMMENT ON COLUMN public.dis_unst_collect_item.title IS '게시물/항목 제목 원문 (수집 CSV Title)';
COMMENT ON COLUMN public.dis_unst_collect_item.src_url IS '출처 상세 페이지/항목 URL';
COMMENT ON COLUMN public.dis_unst_collect_item.inferred_category IS 'label_assist 정규화 카테고리';
COMMENT ON COLUMN public.dis_unst_collect_item.domain IS '도메인 (고용/문화관광/기타)';
COMMENT ON COLUMN public.dis_unst_collect_item.match_confidence IS '분류 신뢰도 0.00~1.00';
COMMENT ON COLUMN public.dis_unst_collect_item.needs_review IS '사람 검토 필요 여부(Y/N)';
COMMENT ON COLUMN public.dis_unst_collect_item.collected_at IS '수집(크롤/호출) 시각';

-- ---------------------------------------------------------------------
--  public.dis_unst_collect_img  (수집 이미지)
-- ---------------------------------------------------------------------
CREATE TABLE public.dis_unst_collect_img (
    img_id            int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- 고유 식별자
    item_id           int4 NOT NULL,                           -- 소속 수집 항목, dis_unst_collect_item.item_id
    img_order         int4 DEFAULT 1,                          -- 항목 내 이미지 순번 (1부터)
    img_url           VARCHAR(1000) NOT NULL,                  -- 원본 이미지 URL (수집 CSV Img-link 분해분)

    local_path        VARCHAR(1000),                           -- 다운로드 저장 경로 (downloader)
    file_ext          VARCHAR(10),                             -- 파일 확장자 (.jpg 등)
    download_yn       CHAR(1) DEFAULT 'N',                     -- 다운로드 완료 여부(Y/N)
    download_err      VARCHAR(500),                            -- 다운로드 실패 사유 (있을 때)

    md5_hash          VARCHAR(32),                             -- 내용 MD5 (dedup 1차)
    sha256_hash       VARCHAR(64),                             -- 내용 SHA256 (dedup 재확인)
    dup_yn            CHAR(1) DEFAULT 'N',                     -- 중복 여부(Y/N) - 보존본은 N
    dup_of_img_id     int4,                                    -- 중복일 때 보존 대상 img_id

    dataset_split     VARCHAR(10),                             -- 학습셋 분할 (train/val/test)
    split_seed        int4,                                    -- 분할 시드 (재현성)

    del_yn            bpchar(1) DEFAULT 'N'::bpchar NULL,      -- 삭제 여부: N(정상), Y(삭제)
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,   -- 등록일시
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,   -- 수정일시
    deleted_at        TIMESTAMPTZ NULL,                        -- 삭제 일시
    created_by        varchar(40) NOT NULL,                    -- 데이터 생성자, "sys_work_type" comm code 참조
    updated_by        varchar(40) NULL,                        -- 데이터 수정자
    deleted_by        varchar(40) NULL,                        -- 삭제 처리자

    CONSTRAINT pkey_dis_unst_collect_img PRIMARY KEY (img_id),
    CONSTRAINT uq_dis_unst_collect_img_url UNIQUE (item_id, img_url),     -- 항목 내 동일 URL 중복 방지
    CONSTRAINT fkey_dis_unst_collect_img_item FOREIGN KEY (item_id)
        REFERENCES public.dis_unst_collect_item(item_id)
);
CREATE INDEX idx_dis_unst_collect_img_item  ON public.dis_unst_collect_img USING btree (item_id);
CREATE INDEX idx_dis_unst_collect_img_md5   ON public.dis_unst_collect_img USING btree (md5_hash);
CREATE INDEX idx_dis_unst_collect_img_split ON public.dis_unst_collect_img USING btree (dataset_split);

COMMENT ON TABLE public.dis_unst_collect_img IS 'SW#2 비정형 수집 이미지 - 다운로드/중복/분할 상태 포함';
COMMENT ON COLUMN public.dis_unst_collect_img.img_id IS '고유 식별자';
COMMENT ON COLUMN public.dis_unst_collect_img.item_id IS '소속 수집 항목, dis_unst_collect_item.item_id';
COMMENT ON COLUMN public.dis_unst_collect_img.img_order IS '항목 내 이미지 순번';
COMMENT ON COLUMN public.dis_unst_collect_img.img_url IS '원본 이미지 URL';
COMMENT ON COLUMN public.dis_unst_collect_img.local_path IS '다운로드 저장 경로';
COMMENT ON COLUMN public.dis_unst_collect_img.file_ext IS '파일 확장자';
COMMENT ON COLUMN public.dis_unst_collect_img.download_yn IS '다운로드 완료 여부(Y/N)';
COMMENT ON COLUMN public.dis_unst_collect_img.download_err IS '다운로드 실패 사유';
COMMENT ON COLUMN public.dis_unst_collect_img.md5_hash IS '내용 MD5 (dedup 1차)';
COMMENT ON COLUMN public.dis_unst_collect_img.sha256_hash IS '내용 SHA256 (dedup 재확인)';
COMMENT ON COLUMN public.dis_unst_collect_img.dup_yn IS '중복 여부(Y/N) - 보존본은 N';
COMMENT ON COLUMN public.dis_unst_collect_img.dup_of_img_id IS '중복일 때 보존 대상 img_id';
COMMENT ON COLUMN public.dis_unst_collect_img.dataset_split IS '학습셋 분할 (train/val/test)';
COMMENT ON COLUMN public.dis_unst_collect_img.split_seed IS '분할 시드 (재현성)';

-- =====================================================================
--  끝.  적용:  psql -d iitp_db -f iitp_db_schemas_init-deletion_and_creation_unst.sql
-- =====================================================================
