-- ## iitp DB Schemas - Mobility(교통약자 이동편의) Initial setup - Creation and Delete if tables exists
-- ## ver 0.0.1 last update data : 2026.07.13
-- ## Only for PostgreSQL
-- ## 3차년도 실증(이동경로 안내) 대비 이동편의 데이터 적재용 스키마
-- ## 소스: GBIS(경기버스정보), 한국철도공사 편의시설정보 API, 국가철도공단 휠체어리프트 CSV, 한국사회보장정보원 장애인편의시설 API


-- ################################################
-- ## 교통 - 버스 노선/배차 메타 (GBIS)
-- ################################################

-- public.tran_bus_route_info definition
-- 안양 연관 노선(regionName 기준) 노선번호/유형/기점종점/운수사/배차간격/첫차막차.
-- 실시간 위치 및 저상버스 여부(lowPlate)는 저장하지 않음 - 서비스가 GBIS API를 직접 호출.

-- Drop table
DROP TABLE IF EXISTS public.tran_bus_route_info;

CREATE TABLE public.tran_bus_route_info (
	route_id bigint NOT NULL ,                      -- GBIS 노선ID (자연키)
	route_name varchar(60) NOT NULL ,               -- 노선번호(명)
	route_type_cd integer NULL ,                    -- 노선유형코드 (GBIS routeTypeCd)
	route_type_name varchar(60) NULL ,              -- 노선유형명
	region_name varchar(200) NULL ,                 -- 운행지역명 (예: 안양,의왕)
	admin_name varchar(100) NULL ,                  -- 관할관청명 (예: 경기도 안양시)
	start_station_id bigint NULL ,                  -- 기점 정류소ID
	start_station_name varchar(200) NULL ,          -- 기점 정류소명
	end_station_id bigint NULL ,                    -- 종점 정류소ID
	end_station_name varchar(200) NULL ,            -- 종점 정류소명
	company_name varchar(200) NULL ,                -- 운수업체명
	company_tel varchar(40) NULL ,                  -- 운수업체 전화번호
	peek_alloc integer NULL ,                       -- 평일 최소 배차시간(분)
	npeek_alloc integer NULL ,                      -- 평일 최대 배차시간(분)
	sat_peek_alloc integer NULL ,                   -- 토요일 최소 배차시간(분)
	sat_npeek_alloc integer NULL ,                  -- 토요일 최대 배차시간(분)
	sun_peek_alloc integer NULL ,                   -- 일요일 최소 배차시간(분)
	sun_npeek_alloc integer NULL ,                  -- 일요일 최대 배차시간(분)
	we_peek_alloc integer NULL ,                    -- 공휴일 최소 배차시간(분)
	we_npeek_alloc integer NULL ,                   -- 공휴일 최대 배차시간(분)
	up_first_time varchar(5) NULL ,                 -- 평일 기점 첫차
	up_last_time varchar(5) NULL ,                  -- 평일 기점 막차
	down_first_time varchar(5) NULL ,               -- 평일 종점 첫차
	down_last_time varchar(5) NULL ,                -- 평일 종점 막차
	low_bus_yn bpchar(1) NULL ,                     -- 저상버스 운영 여부 (현재 미수집, 공식 소스 확보 시 사용)
	base_dt date NULL ,                             -- 데이터 기준 일자(수집일)
	del_yn bpchar(1) DEFAULT 'N' NULL ,             -- 삭제 여부 Y/N
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL ,
	deleted_at timestamptz NULL ,
	created_by varchar(40) NOT NULL ,               -- 데이터 생성자, "sys_work_type" 참조
	updated_by varchar(40) NULL ,
	deleted_by varchar(40) NULL ,
	CONSTRAINT pkey_tran_bus_route_info PRIMARY KEY (route_id)
);
CREATE INDEX idx_tran_bus_route_info_region ON public.tran_bus_route_info USING btree (region_name);
CREATE INDEX idx_tran_bus_route_info_name ON public.tran_bus_route_info USING btree (route_name);


-- ################################################
-- ## POI - 역 단위 교통약자 편의 현황 (한국철도공사 편의시설정보 API)
-- ################################################

-- public.poi_station_access_status definition
-- 코레일 관할 전 역(약 406건). 안양 7역(석수/관악/안양/명학/인덕원/평촌/범계)은 anyang_yn='Y'.

-- Drop table
DROP TABLE IF EXISTS public.poi_station_access_status;

CREATE TABLE public.poi_station_access_status (
	station_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL ,
	stn_cd varchar(16) NOT NULL ,                   -- 코레일 역코드
	stn_name varchar(120) NOT NULL ,                -- 역명
	line_name varchar(60) NULL ,                    -- 선명(보강용, API 미제공 시 NULL)
	elevator_cnt integer NULL ,                     -- 엘리베이터 수
	escalator_cnt integer NULL ,                    -- 에스컬레이터 수
	wheelchair_lift_cnt integer NULL ,              -- 휠체어리프트 수
	dis_slope_yn bpchar(1) NULL ,                   -- 장애인 경사로 유무 Y/N
	dis_toilet_yn bpchar(1) NULL ,                  -- 장애인 화장실 유무 Y/N
	gen_toilet_yn bpchar(1) NULL ,                  -- 일반 화장실 유무 Y/N
	nursing_room_yn bpchar(1) NULL ,                -- 수유실 유무 Y/N
	info_center_yn bpchar(1) NULL ,                 -- 종합안내센터 유무 Y/N
	latitude double precision NULL ,                -- 역 대표 위도(WGS84, 후속 보강)
	longitude double precision NULL ,               -- 역 대표 경도(WGS84, 후속 보강)
	anyang_yn bpchar(1) DEFAULT 'N' NOT NULL ,      -- 안양 관할/인접 실증 대상 역 여부
	base_dt date NULL ,                             -- 데이터 기준 일자
	del_yn bpchar(1) DEFAULT 'N' NULL ,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL ,
	deleted_at timestamptz NULL ,
	created_by varchar(40) NOT NULL ,
	updated_by varchar(40) NULL ,
	deleted_by varchar(40) NULL ,
	CONSTRAINT pkey_poi_station_access_status PRIMARY KEY (station_id)
);
CREATE UNIQUE INDEX uidx_poi_station_access_status_stn_cd ON public.poi_station_access_status USING btree (stn_cd);
CREATE INDEX idx_poi_station_access_status_name ON public.poi_station_access_status USING btree (stn_name);
CREATE INDEX idx_poi_station_access_status_anyang ON public.poi_station_access_status USING btree (anyang_yn);


-- ################################################
-- ## POI - 설비 단위 휠체어리프트 상세 (국가철도공단 CSV)
-- ################################################

-- public.poi_station_wheelchair_lift definition
-- 수도권 1/4호선 휠체어리프트 설비별 상세위치/제원. 분기 1회 파일 갱신 확인.

-- Drop table
DROP TABLE IF EXISTS public.poi_station_wheelchair_lift;

CREATE TABLE public.poi_station_wheelchair_lift (
	lift_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL ,
	oper_org varchar(60) NULL ,                     -- 철도운영기관명 (예: 코레일)
	line_name varchar(60) NOT NULL ,                -- 선명 (예: 1호선)
	stn_name varchar(120) NOT NULL ,                -- 역명
	mng_no varchar(20) NOT NULL ,                   -- 관리번호
	exit_no varchar(20) NULL ,                      -- 출입구번호 (내부 설치 시 "내부")
	detail_loc varchar(300) NULL ,                  -- 상세위치 설명
	length_mm integer NULL ,                        -- 길이(mm)
	width_mm integer NULL ,                         -- 폭(mm)
	start_floor varchar(20) NULL ,                  -- 시작층
	end_floor varchar(20) NULL ,                    -- 종료층
	base_dt date NULL ,                             -- 데이터 기준 일자(파일 기준일)
	del_yn bpchar(1) DEFAULT 'N' NULL ,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL ,
	deleted_at timestamptz NULL ,
	created_by varchar(40) NOT NULL ,
	updated_by varchar(40) NULL ,
	deleted_by varchar(40) NULL ,
	CONSTRAINT pkey_poi_station_wheelchair_lift PRIMARY KEY (lift_id)
);
CREATE UNIQUE INDEX uidx_poi_station_wheelchair_lift_src ON public.poi_station_wheelchair_lift USING btree (line_name, stn_name, mng_no);
CREATE INDEX idx_poi_station_wheelchair_lift_stn ON public.poi_station_wheelchair_lift USING btree (stn_name);


-- ################################################
-- ## POI - 건물 장애인 편의시설 (한국사회보장정보원 API)
-- ################################################

-- public.poi_facility_accessibility definition
-- 전국장애인편의시설 표준 기반. 1차 적재 범위는 안양시 소재 시설(주소 필터).

-- Drop table
DROP TABLE IF EXISTS public.poi_facility_accessibility;

CREATE TABLE public.poi_facility_accessibility (
	facl_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL ,
	facl_inf_id varchar(30) NOT NULL ,              -- 사회보장정보원 시설정보ID (faclInfId)
	wfclt_id varchar(30) NULL ,                     -- 기구표 조회용 관리시설ID (형식 상이, 매핑 확인 후 채움)
	facl_name varchar(200) NOT NULL ,               -- 시설명
	facl_type varchar(100) NULL ,                   -- 시설유형 (faclTyCd)
	addr varchar(600) NULL ,                        -- 소재지 주소 (lcMnad)
	latitude double precision NULL ,                -- 위도(WGS84)
	longitude double precision NULL ,               -- 경도(WGS84)
	estb_date varchar(10) NULL ,                    -- 설치/등록일 (YYYYMMDD)
	elevator_yn bpchar(1) NULL ,                    -- 승강기 Y/N (기구표 파싱)
	dis_toilet_yn bpchar(1) NULL ,                  -- 장애인사용가능화장실 Y/N
	dis_parking_yn bpchar(1) NULL ,                 -- 장애인전용주차구역 Y/N
	entrance_ramp_yn bpchar(1) NULL ,               -- 주출입구 높이차이 제거 Y/N
	entrance_door_yn bpchar(1) NULL ,               -- 주출입구(문) Y/N
	approach_road_yn bpchar(1) NULL ,               -- 주출입구 접근로 Y/N
	eval_info_raw varchar(1000) NULL ,              -- 기구표 원문(콤마 구분 목록)
	base_dt date NULL ,                             -- 데이터 기준 일자
	del_yn bpchar(1) DEFAULT 'N' NULL ,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL ,
	deleted_at timestamptz NULL ,
	created_by varchar(40) NOT NULL ,
	updated_by varchar(40) NULL ,
	deleted_by varchar(40) NULL ,
	CONSTRAINT pkey_poi_facility_accessibility PRIMARY KEY (facl_id)
);
CREATE UNIQUE INDEX uidx_poi_facility_accessibility_inf_id ON public.poi_facility_accessibility USING btree (facl_inf_id);
CREATE INDEX idx_poi_facility_accessibility_location ON public.poi_facility_accessibility USING btree (latitude, longitude);
CREATE INDEX idx_poi_facility_accessibility_type ON public.poi_facility_accessibility USING btree (facl_type);
