-- ## iitp DB Schemas - Discarded db tables
-- ## ver 0.0.1 last update data : 2025.05.07




DROP TABLE IF EXISTS public.stats_dis_house_by_res_age_own;
DROP TABLE IF EXISTS public.stats_dis_house_by_res_own_nonown;
DROP TABLE IF EXISTS public.stats_school_dis_by_type;




-- # public.stats_dis_house_by_res_age_own definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_house_by_res_age_own;

CREATE TABLE public.stats_dis_house_by_res_age_own (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_source_data_info.src_data_id
	target_year int2 NOT NULL, -- 연도 (예: 2024)
	sido_hcode varchar(10) NOT NULL, -- 시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고
	gender bpchar(1) NOT NULL, -- 성별, "gender" common code (예: 남성,여성)
	own_cnt int4 NOT NULL, -- 주택 소유자 수
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_house_by_res_age_own PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_house_by_res_age_own_year_sido_gen ON public.stats_dis_house_by_res_age_own USING btree (target_year, sido_hcode, gender);
COMMENT ON TABLE public.stats_dis_house_by_res_age_own IS '기초-주택-장애인 거주지역/성별 주택소유자수';

-- Column comments

COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.src_data_id IS '소스 데이터 정보 ID, stats_source_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.target_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.sido_hcode IS '시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.gender IS '성별, "gender" common code (예: 남성,여성)';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.own_cnt IS '주택 소유자 수';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_dis_house_by_res_age_own.updated_by IS '데이터 수정자';


-- public.stats_dis_house_by_res_age_own foreign keys

ALTER TABLE public.stats_dis_house_by_res_age_own ADD CONSTRAINT fk_src_d_info_to_st_dis_house_by_res_age_own FOREIGN KEY (src_data_id) REFERENCES public.stats_source_data_info(src_data_id);



-- # public.stats_dis_house_by_res_own_nonown definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_house_by_res_own_nonown;

CREATE TABLE public.stats_dis_house_by_res_own_nonown (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_source_data_info.src_data_id
	target_year int2 NOT NULL, -- 연도 (예: 2024)
	sido_hcode varchar(10) NOT NULL, -- 시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고
	own_cnt int4 NOT NULL, -- 주택 소유자 수
	nonown_cnt int4 NOT NULL, -- 무주택자 수
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_house_by_res_own_nonown PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_house_by_res_own_nonown_year_sido ON public.stats_dis_house_by_res_own_nonown USING btree (target_year, sido_hcode);
COMMENT ON TABLE public.stats_dis_house_by_res_own_nonown IS '기초-주택-장애인거주지역별 주택소유 및 무주택 가구수';

-- Column comments

COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.src_data_id IS '소스 데이터 정보 ID, stats_source_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.target_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.sido_hcode IS '시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.own_cnt IS '주택 소유자 수';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.nonown_cnt IS '무주택자 수';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_dis_house_by_res_own_nonown.updated_by IS '데이터 수정자';


-- public.stats_dis_house_by_res_own_nonown foreign keys

ALTER TABLE public.stats_dis_house_by_res_own_nonown ADD CONSTRAINT fk_src_d_info_to_st_dis_house_by_res_own_nonown FOREIGN KEY (src_data_id) REFERENCES public.stats_source_data_info(src_data_id);



-- # public.stats_school_dis_by_type definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_school_dis_by_type;

CREATE TABLE public.stats_school_dis_by_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_source_data_info.src_data_id
	target_year int2 NOT NULL, -- 연도 (예: 2024)
	cat_main varchar(12) NOT NULL, -- 카테고리 메인,  "sch_dis_type_by_category" comm code ( 예 :성별 ,학교과정별, 배치유형별)
	cat_sub varchar(20) NOT NULL, -- 카테고리 서브, sch_dis_type_by_category 따른 세부(gender, school_level,sch_dis_type_by_cat_place_type 등 )  ( 예 :[남자,여자], [유,초,중,고], [특수학교, 일반학교 특수학급])
	visl_cnt int4 NOT NULL, -- 시각장애자 수
	visl_pct numeric(5,2) NOT NULL, -- 시각장애자 비율(%)
	hear_cnt int4 NOT NULL, -- 청각장애자 수
	hear_pct numeric(5,2) NOT NULL, -- 청각장애자  비율(%)
	intd_cnt int4 NOT NULL, -- 지적장애자 수 
	intd_pct numeric(5,2) NOT NULL, -- 지적장애자  비율(%) 
	phys_cnt int4 NOT NULL, -- 지체장애자 수
	phys_pct numeric(5,2) NOT NULL, -- 지체장애자  비율(%)
	embd_cnt int4 NOT NULL, -- 정서·행동장애자 수
	embd_pct numeric(5,2) NOT NULL, -- 정서·행동장애자  비율(%)
	unti_cnt int4 NOT NULL, -- 자폐성장애자 수
	unti_pct numeric(5,2) NOT NULL, -- 자폐성장애자  비율(%)
	comm_cnt int4 NOT NULL, -- 의사소통장애자 수
	comm_pct numeric(5,2) NOT NULL, -- 의사소통장애자  비율(%)
	lear_cnt int4 NOT NULL, -- 학습장애자 수
	lear_pct numeric(5,2) NOT NULL, -- 학습장애자  비율(%)
	heal_cnt int4 NOT NULL, -- 건강장애자 수
	heal_pct numeric(5,2) NOT NULL, -- 건강장애자  비율(%)
	deve_cnt int4 NOT NULL, -- 발달지체자 수
	deve_pct numeric(5,2) NOT NULL, -- 발달지체자  비율(%)
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_sch_dis_by_type PRIMARY KEY (id)
);
CREATE INDEX idx_st_sch_dis_by_ty_year_cat ON public.stats_school_dis_by_type USING btree (target_year, cat_main, cat_sub);
COMMENT ON TABLE public.stats_school_dis_by_type IS '기조-학교-장애유형별 현황 (학교기준)';

-- Column comments

COMMENT ON COLUMN public.stats_school_dis_by_type.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_school_dis_by_type.src_data_id IS '소스 데이터 정보 ID, stats_source_data_info.src_data_id';
COMMENT ON COLUMN public.stats_school_dis_by_type.target_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_school_dis_by_type.cat_main IS '카테고리 메인,  "sch_dis_type_by_category" comm code  ( 예 :성별 ,학교과정별, 배치유형별)';
COMMENT ON COLUMN public.stats_school_dis_by_type.cat_sub IS '카테고리 서브, sch_dis_type_by_category 따른 세부(gender, school_level,sch_dis_type_by_cat_place_type 등 )  ( 예 :[남자,여자], [유,초,중,고], [특수학교, 일반학교 특수학급])';
COMMENT ON COLUMN public.stats_school_dis_by_type.visl_cnt IS '시각장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.visl_pct IS '시각장애자 비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.hear_cnt IS '청각장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.hear_pct IS '청각장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.intd_cnt IS '지적장애자 수 ';
COMMENT ON COLUMN public.stats_school_dis_by_type.intd_pct IS '지적장애자  비율(%) ';
COMMENT ON COLUMN public.stats_school_dis_by_type.phys_cnt IS '지체장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.phys_pct IS '지체장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.embd_cnt IS '정서·행동장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.embd_pct IS '정서·행동장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.unti_cnt IS '자폐성장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.unti_pct IS '자폐성장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.comm_cnt IS '의사소통장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.comm_pct IS '의사소통장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.lear_cnt IS '학습장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.lear_pct IS '학습장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.heal_cnt IS '건강장애자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.heal_pct IS '건강장애자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.deve_cnt IS '발달지체자 수';
COMMENT ON COLUMN public.stats_school_dis_by_type.deve_pct IS '발달지체자  비율(%)';
COMMENT ON COLUMN public.stats_school_dis_by_type.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_school_dis_by_type.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_school_dis_by_type.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_school_dis_by_type.updated_by IS '데이터 수정자';


-- public.stats_school_dis_by_type foreign keys

ALTER TABLE public.stats_school_dis_by_type ADD CONSTRAINT fk_st_sch_dis_by_type FOREIGN KEY (src_data_id) REFERENCES public.stats_source_data_info(src_data_id);

