-- ## iitp DB Schemas - Initial setup - Creation and Delete if tables exists 
-- ## ver 0.0.1 last updated data : 2025.09.15
-- ## Only for PostgreSQL
-- ## 장애인 자립 지원 허브 웹 플랫폼 용 
-- ##




-- ################################################
-- ## 시스템 테이블 생성 
-- ################################################



-- #### [주의] 통계 데이터 수집으로 sys_stats_src_api_info, stats_src_data_info 테이블의 데이터가 변경되면, sys_data_summary_info 테이블 데이터도 update 해야 함.
-- #### [주의] mv_poi, poi_*,  emp_dis_* 테이블의 데이터가 변경되면, sys_data_summary_info 테이블 데이터도 update 해야 함.

-- # public.sys_data_summary_info definition
DROP TABLE IF EXISTS public.sys_data_summary_info;


CREATE TABLE public.sys_data_summary_info (
	data_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	target_data_id int4 NOT NULL, --  Target Data info sys ID, data_type 에 따라서 id 참조. 예) stats_src_data_info.src_data_id
	data_type varchar(16) NOT NULL, -- Data Type (stats/poi/emp) 
    self_rel_type varchar(16),      -- 자립 테마 타입 (physical,emotional, economic,social)
	self_rel_type_name varchar(16), -- 자립 테마 타입명 (신체적 자립/정서적 자립/경제적 자립/사회적 자립)
	
	title varchar(300) NOT NULL, -- 데이터명
	sys_tbl_id varchar(40) NOT NULL, -- iitp 데이터 테이블 ID
	
	src_org_name varchar(12) NOT NULL,      -- 데이터 제공처(기관명)
	src_latest_chn_dt varchar(12) NOT NULL, -- 수집기관 최종 자료갱신일 (예:2024-07-19)
	
	sys_data_ref_dt varchar(12) NULL, 		-- 데이터를 iitp 시스템에서 마지막 수집/참조 일자 (예:2024-07-19)
	sys_data_reg_dt varchar(12) NOT NULL,   -- 데이터를 iitp 시스템에 등록한 일자 (예:2024-07-19) 
	
	data_keywords varchar(220),        -- 데이터 키워드 (최대 3개), 데이터 포맷 :: [,,] 형식
	data_format varchar(8),            -- 제공 데이터 포맷 (csv)
	
	data_desc varchar(300),            -- 데이터 설명
	data_usage_scope varchar(300),     -- 이용 데이터 범위 설명
	
	status char(1) DEFAULT 'A'  NOT NULL, -- 데이터 상태,  "data_status" comm code 참조
	del_yn char(1) DEFAULT 'N'::bpchar NOT NULL, -- 삭제여부 (Y: 삭제)
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP, -- 레코드 수정 시각
	deleted_at timestamptz NULL, -- 삭제 일시 (논리 삭제 시 기록)
	CONSTRAINT pkey_sys_data_sumary_info PRIMARY KEY (data_id)
);
CREATE UNIQUE INDEX uidx_sys_data_sumary_info_sys_tbl_id ON public.sys_data_summary_info USING btree (sys_tbl_id);
CREATE INDEX  idx_sys_data_sumary_info_title ON public.sys_data_summary_info USING btree (title);
CREATE INDEX  idx_sys_data_sumary_info_data_type ON public.sys_data_summary_info USING btree (data_type);
CREATE INDEX  idx_sys_data_sumary_info_self_rel_type ON public.sys_data_summary_info USING btree (self_rel_type);



COMMENT ON TABLE public.sys_data_summary_info IS 'IITP 전체 데이터별 요약 정보';

-- Column comments
COMMENT ON COLUMN public.sys_data_summary_info.data_id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.sys_data_summary_info.target_data_id IS 'Target Data info sys ID, target_data_type 에 따라서 id 참조. 예) stats_src_data_info.src_data_id';

COMMENT ON COLUMN public.sys_data_summary_info.data_type IS 'Target Data Type (stats/poi/emp)';
COMMENT ON COLUMN public.sys_data_summary_info.self_rel_type IS '자립 테마 타입 (physical,emotional, economic,social)';
COMMENT ON COLUMN public.sys_data_summary_info.self_rel_type_name IS '자립 테마 타입명 (신체적 자립/정서적 자립/경제적 자립/사회적 자립)';


COMMENT ON COLUMN public.sys_data_summary_info.title IS '데이터명';
COMMENT ON COLUMN public.sys_data_summary_info.sys_tbl_id IS 'iitp 데이터 테이블 ID';

COMMENT ON COLUMN public.sys_data_summary_info.src_org_name IS '데이터 제공처(기관명)';
COMMENT ON COLUMN public.sys_data_summary_info.src_latest_chn_dt IS '수집기관 최종 자료갱신일 (예:2024-07-19)';

COMMENT ON COLUMN public.sys_data_summary_info.sys_data_ref_dt IS '데이터를 iitp 시스템에서 마지막 수집/참조 일자 (예:2024-07-19)';
COMMENT ON COLUMN public.sys_data_summary_info.sys_data_reg_dt IS '데이터를 iitp 시스템에 등록한 일자 (예:2024-07-19)';

COMMENT ON COLUMN public.sys_data_summary_info.data_keywords IS '데이터 키워드 (최대 3개), 데이터 포맷 :: [,,] 형식';
COMMENT ON COLUMN public.sys_data_summary_info.data_format IS '제공 데이터 포맷 (csv)';

COMMENT ON COLUMN public.sys_data_summary_info.data_desc IS '데이터 설명';
COMMENT ON COLUMN public.sys_data_summary_info.data_usage_scope IS '이용 데이터 범위 설명';

COMMENT ON COLUMN public.sys_data_summary_info.status IS '"data_status" comm code 참조';
COMMENT ON COLUMN public.sys_data_summary_info.del_yn IS '삭제여부 (Y: 삭제)';

COMMENT ON COLUMN public.sys_data_summary_info.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.sys_data_summary_info.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.sys_data_summary_info.deleted_at IS '삭제 일시 (논리 삭제 시 기록)';
