-- ## iitp DB Schemas - POI Initial setup - Creation and Delete if tables exists 
-- ## ver 0.0.5 last update data : 2025.09.08
-- ## Only for PostgreSQL




-- ################################################
-- ## 기초 데이터 - 관광 관련 POI 정보
-- ################################################

-- public.mv_poi definition

-- Drop table
DROP TABLE IF EXISTS public.mv_poi;

CREATE TABLE public.mv_poi ( 
	poi_id bigserial NOT NULL , 
	language_code varchar(10) NOT NULL , 
	title varchar(200) NOT NULL , 
	summary text NULL , 
	basic_info text NULL , 
	address_code varchar(10) NULL , 
	address_road varchar(200) NULL , 
	address_detail varchar(200) NULL , 
	sido_code varchar(12) NULL , 
	latitude numeric(10, 8) NULL , 
	longitude numeric(11, 8) NULL , 
	detail_json jsonb NULL , 
	search_filter_json jsonb NULL , 
	publish_date timestamp NULL , 
	update_date timestamp NULL , 
	create_date timestamp DEFAULT CURRENT_TIMESTAMP NULL , 
	is_deleted varchar(1) DEFAULT 'N'::bpchar NOT NULL , 
	is_published varchar(1) DEFAULT 'N'::bpchar NOT NULL , 
	source_organization varchar(100) NULL , 
	source_id varchar(50) NULL , 
	CONSTRAINT poi_pkey PRIMARY KEY (poi_id)
);
CREATE INDEX idx_address_code ON public.mv_poi USING btree (address_code);
CREATE INDEX idx_language_code ON public.mv_poi USING btree (language_code);
CREATE INDEX idx_location ON public.mv_poi USING btree (latitude, longitude);
CREATE INDEX idx_publish_status ON public.mv_poi USING btree (is_published, is_deleted);
CREATE INDEX idx_search_filter_json_gin ON public.mv_poi USING gin (search_filter_json);
CREATE INDEX idx_search_filter_json_path ON public.mv_poi USING gin (((search_filter_json -> 'search_filter'::text)));
COMMENT ON TABLE public.mv_poi IS '이동형 POI';

-- Column comments

COMMENT ON COLUMN public.mv_poi.poi_id IS 'POI 아이디';
COMMENT ON COLUMN public.mv_poi.language_code IS '언어 코드';
COMMENT ON COLUMN public.mv_poi.title IS '제목';
COMMENT ON COLUMN public.mv_poi.summary IS '요약 정보';
COMMENT ON COLUMN public.mv_poi.basic_info IS '기본 정보';
COMMENT ON COLUMN public.mv_poi.address_code IS '주소 코드 ';
COMMENT ON COLUMN public.mv_poi.address_road IS '도로명 주소';
COMMENT ON COLUMN public.mv_poi.address_detail IS '상세 주소';
COMMENT ON COLUMN public.mv_poi.latitude IS '위도';
COMMENT ON COLUMN public.mv_poi.longitude IS '경도';
COMMENT ON COLUMN public.mv_poi.detail_json IS '상세 정보';
COMMENT ON COLUMN public.mv_poi.search_filter_json IS '검색 필터 정보';
COMMENT ON COLUMN public.mv_poi.publish_date IS '발행일';
COMMENT ON COLUMN public.mv_poi.update_date IS '수정일';
COMMENT ON COLUMN public.mv_poi.create_date IS '생성일';
COMMENT ON COLUMN public.mv_poi.is_deleted IS '삭제 여부(Y/N)';
COMMENT ON COLUMN public.mv_poi.is_published IS '발행 여부(Y/N)';
COMMENT ON COLUMN public.mv_poi.source_organization IS '출처 기관';
COMMENT ON COLUMN public.mv_poi.source_id IS '출처 아이디';





-- ################################################
-- ## 기초 데이터 - 편의시설 관려 POI 정보
-- ################################################


-- #### 공중 화장실 위치 정보 테이블  ####

-- public.poi_public_toilet_info definition

-- Drop table
DROP TABLE IF EXISTS public.poi_public_toilet_info;

CREATE TABLE public.poi_public_toilet_info (
    toilet_id       int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,   -- 고유 식별자 (자동 증가)
	sido_code				VARCHAR(12)  NOT NULL,                           -- 내부 시도 코드, "sido_code" comm code 참조 
    toilet_name             VARCHAR(300) NOT NULL,                           -- 화장실명
    toilet_type             VARCHAR(50) NOT NULL,                            -- 구분 (예: 공중화장실)
	basis                   VARCHAR(300) ,                           -- 설치 근거
    addr_road               VARCHAR(600),                           -- 소재지 도로명 주소
    addr_jibun              VARCHAR(600),                           -- 소재지 지번 주소

    m_toilet_count              INTEGER,                                -- 남성용 대변기 수
    m_urinal_count              INTEGER,                                -- 남성용 소변기 수
    m_dis_toilet_count          INTEGER,                                -- 남성용 장애인 대변기 수
    m_dis_urinal_count          INTEGER,                                -- 남성용 장애인 소변기 수
    m_child_toilet_count        INTEGER,                                -- 남성용 어린이 대변기 수
    m_child_urinal_count        INTEGER,                                -- 남성용 어린이 소변기 수

    f_toilet_count            INTEGER,                                -- 여성용 대변기 수
    f_dis_toilet_count        INTEGER,                                -- 여성용 장애인 대변기 수
    f_child_toilet_count      INTEGER,                                -- 여성용 어린이 대변기 수

    managing_org                   VARCHAR(300),                           -- 관리기관명
    phone_number                   VARCHAR(32),                            -- 전화번호

    open_time                      VARCHAR(100),                           -- 개방시간 (예: "24시간", "06:00~22:00")
    open_time_detail               VARCHAR(300),                           -- 개방시간 상세

    install_dt                   VARCHAR(10),                            -- 설치 연월 (YYYY-MM)

    latitude                       DOUBLE PRECISION,                       -- 위도 (WGS84)
    longitude                      DOUBLE PRECISION,                       -- 경도 (WGS84)

    owner_type                     VARCHAR(300),                           -- 화장실 소유 구분 (예: 공공기관-지방자치단체)
    waste_process_type             VARCHAR(100),                           -- 오물 처리 방식 (예: 수거식)

    safety_target_yn              CHAR(1),                                 -- 안전관리시설설치대상여부 (Y/N)
    emg_bell_yn            CHAR(1),                                        -- 비상벨 설치 여부 (Y/N)
    emg_bell_location       VARCHAR(300),                                  -- 비상벨 설치 장소

    cctv_yn                        CHAR(1),                                 -- 화장실 입구 CCTV 설치 유무 (Y/N)
    diaper_table_yn               CHAR(1),                                 -- 기저귀 교환대 유무 (Y/N)
    diaper_table_location         VARCHAR(300),                            -- 기저귀 교환대 장소
    
    remodeled_dt                 VARCHAR(12),                                   -- 리모델링 연월 (YYYY-MM-DD)
    base_dt                    DATE,                                   -- 데이터 기준 일자
	
    del_yn bpchar(1) DEFAULT 'N'::bpchar NULL, -- 삭제 여부: N(정상), Y(삭제)
    
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP, -- 레코드 수정 시각
	deleted_at timestamptz NULL, -- 삭제 일시 (논리 삭제 시 기록)
	created_by varchar(40) NOT NULL, -- 데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조
	updated_by varchar(40) NULL, -- 데이터 수정자
	deleted_by varchar(40) NULL, -- 삭제 처리자
	
	CONSTRAINT pkey_poi_public_toilet_info PRIMARY KEY (toilet_id)
);
CREATE INDEX idx_poi_public_toilet_info_sido ON public.poi_public_toilet_info USING btree (sido_code);
CREATE INDEX idx_poi_public_toilet_info_location ON public.poi_public_toilet_info USING btree (latitude, longitude);
CREATE INDEX idx_poi_public_toilet_info_type_name ON public.poi_public_toilet_info USING btree (toilet_type, toilet_name);


COMMENT ON TABLE public.poi_public_toilet_info IS '공중 화장실 위치 및 시설 정보';

COMMENT ON COLUMN public.poi_public_toilet_info.toilet_id IS '공중 화장실 고유 ID (자동 증가)';
COMMENT ON COLUMN public.poi_public_toilet_info.sido_code IS '내부 시도 코드, "sido_code" comm code 참조';
COMMENT ON COLUMN public.poi_public_toilet_info.toilet_type IS '화장실 구분 (예: 공중화장실)';
COMMENT ON COLUMN public.poi_public_toilet_info.basis IS '화장실 설치 근거';
COMMENT ON COLUMN public.poi_public_toilet_info.toilet_name IS '화장실명';
COMMENT ON COLUMN public.poi_public_toilet_info.addr_road IS '소재지 도로명 주소';
COMMENT ON COLUMN public.poi_public_toilet_info.addr_jibun IS '소재지 지번 주소';

COMMENT ON COLUMN public.poi_public_toilet_info.m_toilet_count IS '남성용 대변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.m_urinal_count IS '남성용 소변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.m_dis_toilet_count IS '남성용 장애인 대변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.m_dis_urinal_count IS '남성용 장애인 소변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.m_child_toilet_count IS '남성용 어린이 대변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.m_child_urinal_count IS '남성용 어린이 소변기 수';

COMMENT ON COLUMN public.poi_public_toilet_info.f_toilet_count IS '여성용 대변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.f_dis_toilet_count IS '여성용 장애인 대변기 수';
COMMENT ON COLUMN public.poi_public_toilet_info.f_child_toilet_count IS '여성용 어린이 대변기 수';

COMMENT ON COLUMN public.poi_public_toilet_info.managing_org IS '관리 기관명';
COMMENT ON COLUMN public.poi_public_toilet_info.phone_number IS '관리 기관 전화번호';

COMMENT ON COLUMN public.poi_public_toilet_info.open_time IS '개방 시간';
COMMENT ON COLUMN public.poi_public_toilet_info.open_time_detail IS '개방 시간 상세';

COMMENT ON COLUMN public.poi_public_toilet_info.install_dt IS '설치 연월 (YYYY-MM)';

COMMENT ON COLUMN public.poi_public_toilet_info.latitude IS 'WGS84 기준 위도';
COMMENT ON COLUMN public.poi_public_toilet_info.longitude IS 'WGS84 기준 경도';

COMMENT ON COLUMN public.poi_public_toilet_info.owner_type IS '화장실 소유 구분';
COMMENT ON COLUMN public.poi_public_toilet_info.waste_process_type IS '오물 처리 방식';

COMMENT ON COLUMN public.poi_public_toilet_info.safety_target_yn IS '안전관리시설 설치 대상 여부 (Y/N)';
COMMENT ON COLUMN public.poi_public_toilet_info.emg_bell_yn IS '비상벨 설치 여부 (Y/N)';
COMMENT ON COLUMN public.poi_public_toilet_info.emg_bell_location IS '비상벨 설치 장소';

COMMENT ON COLUMN public.poi_public_toilet_info.cctv_yn IS '화장실 입구 CCTV 설치 유무 (Y/N)';
COMMENT ON COLUMN public.poi_public_toilet_info.diaper_table_yn IS '기저귀 교환대 유무 (Y/N)';
COMMENT ON COLUMN public.poi_public_toilet_info.diaper_table_location IS '기저귀 교환대 설치 장소';

COMMENT ON COLUMN public.poi_public_toilet_info.remodeled_dt IS '리모델링 연월';
COMMENT ON COLUMN public.poi_public_toilet_info.base_dt IS '데이터 기준 일자';
COMMENT ON COLUMN public.poi_public_toilet_info.del_yn IS '삭제 여부: N(정상), Y(삭제)';

COMMENT ON COLUMN public.poi_public_toilet_info.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.poi_public_toilet_info.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.poi_public_toilet_info.deleted_at IS '삭제 일시 (논리 삭제 시 기록)';
COMMENT ON COLUMN public.poi_public_toilet_info.created_by IS '데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조';
COMMENT ON COLUMN public.poi_public_toilet_info.updated_by IS '데이터 수정자';
COMMENT ON COLUMN public.poi_public_toilet_info.deleted_by IS '삭제 처리자';



-- #### 서울시 지하철역 엘리베이터 위치 정보 테이블  ####

-- public.poi_subway_elevator definition

-- Drop table
DROP TABLE IF EXISTS public.poi_subway_elevator;

CREATE TABLE poi_subway_elevator (
    subway_id             int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,   -- 고유 식별자
    sido_code				VARCHAR(12)  NOT NULL,                           -- 내부 시도 코드, "sido_code" comm code 참조 
	node_link_type         VARCHAR(20) NOT NULL,                                   -- 노드링크 유형 (예: NODE)
    -- geom                   geometry(Point, 4326),                         -- WKT 기반 위치정보 (SRID 4326 사용)
	node_wkt                VARCHAR(100),                         -- WKT 기반 위치정보 (SRID 4326 사용)
    node_id                BIGINT NOT NULL,                                        -- 노드 ID
    node_type_code         INTEGER NOT NULL,                                       -- 노드 유형 코드 (예: 0(일반노드), 1(지하철 출입구), 2(버스 정류장), 3(지하보도 출입구))
	node_type_name         VARCHAR(60) NOT NULL,                                       -- 노드 유형 이름 (예: 0(일반노드), 1(지하철 출입구), 2(버스 정류장), 3(지하보도 출입구))
    
    sigungu_code           VARCHAR(16),                                   -- 시군구 코드 (법정동 코드 앞 5자리 + 00000)
    sigungu_name           VARCHAR(100),                                  -- 시군구 명 (예: 종로구)
    eupmyeondong_code      VARCHAR(16),                                   -- 읍면동 코드 (법정동 전체 코드)
    eupmyeondong_name      VARCHAR(100),                                  -- 읍면동 명 (예: 종로2가)
    
    station_code           VARCHAR(16),                                   -- 지하철역 코드 (예: 267)
    station_name           VARCHAR(120),                                  -- 지하철역 명 (예: 혜화)
	
	latitude                       DOUBLE PRECISION,                       -- 위도 (WGS84)
    longitude                      DOUBLE PRECISION,                       -- 경도 (WGS84)
	
	base_dt                      VARCHAR(12),                                   -- 데이터 기준 일자
	del_yn bpchar(1) DEFAULT 'N'::bpchar NULL, -- 삭제 여부: N(정상), Y(삭제)
	
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,         -- 생성일시
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,          -- 수정일시
    deleted_at timestamptz NULL, -- 삭제 일시 (논리 삭제 시 기록)
	created_by varchar(40) NOT NULL, -- 데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조
	updated_by varchar(40) NULL, -- 데이터 수정자
	deleted_by varchar(40) NULL, -- 삭제 처리자
	
	CONSTRAINT pkey_poi_subway_elevator PRIMARY KEY (subway_id)
);
CREATE UNIQUE INDEX uidx_poi_subway_elevator_node_id ON public.poi_subway_elevator USING btree (node_id);
-- CREATE INDEX idx_poi_subway_elevator_geom ON poi_subway_elevator USING GIST (geom);
CREATE INDEX idx_poi_subway_elevator_location ON public.poi_subway_elevator USING btree (latitude, longitude);
CREATE INDEX idx_poi_subway_elevator_info_station ON public.poi_subway_elevator USING btree (sido_code, station_code, station_name);




COMMENT ON TABLE public.poi_subway_elevator IS '서울시 지하철역 엘리베이터 위치 정보';
COMMENT ON COLUMN public.poi_subway_elevator.sido_code IS '내부 시도 코드, "sido_code" comm code 참조';
COMMENT ON COLUMN public.poi_subway_elevator.node_link_type IS '노드링크 유형 (예: NODE)';
COMMENT ON COLUMN public.poi_subway_elevator.node_wkt IS '엘리베이터 위치 string (WKT 형식의 좌표 - 위경도)';
-- COMMENT ON COLUMN public.poi_subway_elevator.geom IS '엘리베이터 위치 (WKT 형식의 좌표 - 위경도)';
COMMENT ON COLUMN public.poi_subway_elevator.node_id IS '노드 ID';
COMMENT ON COLUMN public.poi_subway_elevator.node_type_code IS '노드 유형 코드 (예: 0(일반노드), 1(지하철 출입구), 2(버스 정류장), 3(지하보도 출입구))';
COMMENT ON COLUMN public.poi_subway_elevator.node_type_name IS '노드 유형 코드 (예: 0(일반노드), 1(지하철 출입구), 2(버스 정류장), 3(지하보도 출입구))';
COMMENT ON COLUMN public.poi_subway_elevator.sigungu_code IS '시군구 코드 (10자리 법정동 코드)';
COMMENT ON COLUMN public.poi_subway_elevator.sigungu_name IS '시군구 명칭 (예: 종로구)';
COMMENT ON COLUMN public.poi_subway_elevator.eupmyeondong_code IS '읍면동 코드 (법정동 전체 코드)';
COMMENT ON COLUMN public.poi_subway_elevator.eupmyeondong_name IS '읍면동 명칭 (예: 종로2가)';
COMMENT ON COLUMN public.poi_subway_elevator.station_code IS '지하철역 코드';
COMMENT ON COLUMN public.poi_subway_elevator.station_name IS '지하철역 명칭';
COMMENT ON COLUMN public.poi_subway_elevator.latitude IS 'WGS84 기준 위도';
COMMENT ON COLUMN public.poi_subway_elevator.longitude IS 'WGS84 기준 경도';
COMMENT ON COLUMN public.poi_subway_elevator.base_dt IS '데이터 기준 일자';

COMMENT ON COLUMN public.poi_subway_elevator.del_yn IS '삭제 여부: N(정상), Y(삭제)';
COMMENT ON COLUMN public.poi_subway_elevator.created_at IS '데이터 생성일시';
COMMENT ON COLUMN public.poi_subway_elevator.updated_at IS '데이터 수정일시';
COMMENT ON COLUMN public.poi_subway_elevator.deleted_at IS '삭제 일시 (논리 삭제 시 기록)';
COMMENT ON COLUMN public.poi_subway_elevator.created_by IS '데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조';
COMMENT ON COLUMN public.poi_subway_elevator.updated_by IS '데이터 수정자';
COMMENT ON COLUMN public.poi_subway_elevator.deleted_by IS '삭제 처리자';



-- #### 무장애 관광지 시설 정보 테이블  ####

-- public.poi_tour_bf_facility definition

-- Drop table
DROP TABLE IF EXISTS public.poi_tour_bf_facility;

CREATE TABLE public.poi_tour_bf_facility (
    fclt_id       int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,   -- 고유 식별자
	sido_code		  VARCHAR(12)  NOT NULL,                           -- 내부 시도 코드, "sido_code" comm code 참조 
    fclt_name         VARCHAR(200) NOT NULL,                                -- 무장애 관광지명
    toilet_yn         CHAR(1),                                              -- 장애인 화장실 여부
    elevator_yn       CHAR(1),                                              -- 엘리베이터 여부
    parking_yn        CHAR(1),                                              -- 장애인 주차장 여부
    slope_yn          CHAR(1),                                              -- 경사로 여부
    subway_yn         CHAR(1),                                              -- 지하철 접근성 여부
    bus_stop_yn       CHAR(1),                                              -- 버스 정류장 접근성 여부
    wheelchair_rent_yn CHAR(1),                                             -- 휠체어 대여 여부
    tactile_map_yn    CHAR(1),                                              -- 촉지도식 안내판 설치 여부
    audio_guide_yn    CHAR(1),                                              -- 오디오 가이드 제공 여부
    nursing_room_yn   CHAR(1),                                              -- 아기 돌봄/수유실 여부
    accessible_room_yn CHAR(1),                                             -- 무장애 객실 여부
    stroller_rent_yn  CHAR(1),                                              -- 유아차 대여 여부
	
	addr_road               VARCHAR(600),                           -- 소재지 도로명 주소
    addr_jibun              VARCHAR(600),                           -- 소재지 지번 주소
	
	latitude          DOUBLE PRECISION,                       -- 위도 (WGS84)
    longitude         DOUBLE PRECISION,                       -- 경도 (WGS84)
	base_dt           DATE,                                   -- 데이터 기준 일자
	
	del_yn bpchar(1) DEFAULT 'N'::bpchar NULL, -- 삭제 여부: N(정상), Y(삭제)
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,                 -- 등록일시
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP ,                 -- 수정일시
    deleted_at TIMESTAMPTZ NULL, -- 삭제 일시 (논리 삭제 시 기록)
    created_by varchar(40) NOT NULL, -- 데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조
	updated_by varchar(40) NULL, -- 데이터 수정자
	deleted_by varchar(40) NULL, -- 삭제 처리자
    
	CONSTRAINT pkey_poi_tour_bf_facility PRIMARY KEY (fclt_id)
);
CREATE INDEX idx_poi_tour_bf_facility_sido ON public.poi_tour_bf_facility USING btree (sido_code);
CREATE INDEX idx_poi_tour_bf_facility_f_name ON public.poi_tour_bf_facility USING btree (fclt_name);

COMMENT ON TABLE public.poi_tour_bf_facility IS '무장애(Barrier Free) 관광지 시설 정보';

COMMENT ON COLUMN public.poi_tour_bf_facility.sido_code IS '내부 시도 코드, "sido_code" comm code 참조';
COMMENT ON COLUMN public.poi_tour_bf_facility.fclt_id IS '고유 식별자';
COMMENT ON COLUMN public.poi_tour_bf_facility.fclt_name IS '무장애 관광지명';
COMMENT ON COLUMN public.poi_tour_bf_facility.toilet_yn IS '장애인 화장실 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.elevator_yn IS '엘리베이터 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.parking_yn IS '장애인 주차장 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.slope_yn IS '경사로 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.subway_yn IS '지하철 접근성 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.bus_stop_yn IS '버스 정류장 접근성 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.wheelchair_rent_yn IS '휠체어 대여 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.tactile_map_yn IS '촉지도식 안내판 설치 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.audio_guide_yn IS '오디오 가이드 제공 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.nursing_room_yn IS '아기 돌봄/수유실 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.accessible_room_yn IS '무장애 객실 여부';
COMMENT ON COLUMN public.poi_tour_bf_facility.stroller_rent_yn IS '유아차 대여 여부';

COMMENT ON COLUMN public.mv_poi.address_road IS '도로명 주소';
COMMENT ON COLUMN public.mv_poi.address_detail IS '상세 주소';

COMMENT ON COLUMN public.poi_tour_bf_facility.latitude IS 'WGS84 기준 위도';
COMMENT ON COLUMN public.poi_tour_bf_facility.longitude IS 'WGS84 기준 경도';
COMMENT ON COLUMN public.poi_tour_bf_facility.base_dt IS '데이터 기준 일자';

COMMENT ON COLUMN public.poi_tour_bf_facility.del_yn IS '삭제 여부: N(정상), Y(삭제)';
COMMENT ON COLUMN public.poi_tour_bf_facility.created_at IS '등록일시';
COMMENT ON COLUMN public.poi_tour_bf_facility.updated_at IS '수정일시';
COMMENT ON COLUMN public.poi_tour_bf_facility.deleted_at IS '삭제 일시 (논리 삭제 시 기록)';
COMMENT ON COLUMN public.poi_tour_bf_facility.created_by IS '데이터 생성자 (SYS-BACH, SYS-MANUAL, BY-USER, admin name), "sys_work_type" comm code 참조';
COMMENT ON COLUMN public.poi_tour_bf_facility.updated_by IS '데이터 수정자';
COMMENT ON COLUMN public.poi_tour_bf_facility.deleted_by IS '삭제 처리자';