-- ## iitp DB Schemas - Creation and Delete if tables exists
-- ## ver 0.0.1 last update data : 2025.05.07


-- # public.sys_ext_api_info definition

-- Drop table if table exists
DROP TABLE IF EXISTS public.sys_ext_api_info;

-- Create table
CREATE TABLE public.sys_ext_api_info (
	ext_api_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	if_name varchar(100) NOT NULL, -- 연동 이름
	ext_sys varchar(50) NOT NULL, -- 연동 시스템 Code , "ext_sys_code" comm code 참조
	ext_url varchar(300) NOT NULL, -- 연동 url
	auth varchar(100) NULL, -- 내부 키로 암호화된 인증키 
	data_format varchar(20) NULL, -- 데이타 포멧 ( 예: JSON, XML 등)
	last_sync_time timestamptz NULL, -- 마지막 데이터 수집 시간
	memo varchar(100) NULL,
	is_deleted bpchar(1) DEFAULT 'N'::bpchar NOT NULL, -- 삭제여부 (Y: 삭제)
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	deleted_at timestamptz NULL, -- 레코드 수정 시각
	created_by varchar(40) NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	deleted_by varchar(40) NULL, -- 데이터 삭제자
	CONSTRAINT pkey_sys_ext_api_info PRIMARY KEY (ext_api_id)
);
CREATE UNIQUE INDEX uidx_sys_ext_api_info_if_name ON public.sys_ext_api_info USING btree (if_name);
CREATE INDEX idx_sys_ext_api_info_ext ON public.sys_ext_api_info USING btree (ext_sys);
COMMENT ON TABLE public.sys_ext_api_info IS 'SYS-외부 연동 open api  정보 테이블 ';

-- Column comments

COMMENT ON COLUMN public.sys_ext_api_info.ext_api_id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.sys_ext_api_info.if_name IS '연동 이름';
COMMENT ON COLUMN public.sys_ext_api_info.ext_sys IS '연동 시스템 Code , "ext_sys_code" comm code 참조';
COMMENT ON COLUMN public.sys_ext_api_info.ext_url IS '연동 url';
COMMENT ON COLUMN public.sys_ext_api_info.auth IS '내부 키로 암호화된 인증키 ';
COMMENT ON COLUMN public.sys_ext_api_info.data_format IS '데이타 포멧 ( 예: JSON, XML 등)';
COMMENT ON COLUMN public.sys_ext_api_info.last_sync_time IS '마지막 데이터 수집 시간';
COMMENT ON COLUMN public.sys_ext_api_info.is_deleted IS '삭제여부 (Y: 삭제)';
COMMENT ON COLUMN public.sys_ext_api_info.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.sys_ext_api_info.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.sys_ext_api_info.deleted_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.sys_ext_api_info.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.sys_ext_api_info.updated_by IS '데이터 수정자';
COMMENT ON COLUMN public.sys_ext_api_info.deleted_by IS '데이터 삭제자';



-- # public.stats_src_data_info definition


-- First, delete the related foreign key link table.
--- FR_KEY with stats_src_data_info
-- 주거 자립 현황
DROP TABLE IF EXISTS public.stats_dis_reg_natl_by_new;
DROP TABLE IF EXISTS public.stats_dis_reg_sido_by_age_type_sev_gen;
DROP TABLE IF EXISTS public.stats_dis_reg_natl_by_age_type_sev_gen;
DROP TABLE IF EXISTS public.stats_dis_life_supp_need_lvl;
DROP TABLE IF EXISTS public.stats_dis_life_maincarer;
DROP TABLE IF EXISTS public.stats_dis_life_1stcarer;
DROP TABLE IF EXISTS public.stats_dis_life_supp_field;
-- 건강 관리 현황
DROP TABLE IF EXISTS public.stats_dis_hlth_medical_usage;
DROP TABLE IF EXISTS public.stats_dis_hlth_disease_cost_sub;
DROP TABLE IF EXISTS public.stats_dis_hlth_sport_exec_type;
DROP TABLE IF EXISTS public.stats_dis_hlth_exrc_best_aid;
-- 보조기기 사용 현황
DROP TABLE IF EXISTS public.stats_dis_aid_device_usage;
DROP TABLE IF EXISTS public.stats_dis_aid_device_need;
-- 진로 교육 현황
DROP TABLE IF EXISTS public.stats_dis_edu_voca_exec;
DROP TABLE IF EXISTS public.stats_dis_edu_voca_exec_way;
-- 고용 현황
DROP TABLE IF EXISTS public.stats_dis_emp_natl;
DROP TABLE IF EXISTS public.stats_dis_emp_natl_public;
DROP TABLE IF EXISTS public.stats_dis_emp_natl_private;
DROP TABLE IF EXISTS public.stats_dis_emp_natl_gov_org;
DROP TABLE IF EXISTS public.stats_dis_emp_natl_dis_type_sev;
DROP TABLE IF EXISTS public.stats_dis_emp_natl_dis_type_indust;
-- 사회망 현황
DROP TABLE IF EXISTS public.stats_dis_soc_partic_freq;
DROP TABLE IF EXISTS public.stats_dis_soc_contact_cntfreq;
-- 편의 시설 제공 현황
DROP TABLE IF EXISTS public.stats_dis_fclty_welfare_usage; 
 

-- Drop table

DROP TABLE IF EXISTS public.stats_src_data_info;

-- Create table
CREATE TABLE public.stats_src_data_info (
	src_data_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	ext_api_id int4 NOT NULL, -- 연동 시스템 정보 ID, sys_ext_api_info.ext_api_id
	ext_sys varchar(10) NULL, -- 데이터 수집한 외부 시스템 코드, "ext_sys_code" comm code 참조. ext_api_id.ext_sys_code 코드와 동일
	stat_title varchar(250) NOT NULL, -- 데이터명
	src_org varchar(50) NOT NULL, -- 작성기관 코드 , "stats_data_src_org" comm code 참조
	src_title varchar(200) NOT NULL, -- 조사명
	src_pub_dt date NOT NULL, -- 작성시점
	collect_cycle int2 not NULL, -- 데이터 수집 주기 (개월 단위, 연간이면 12, 2년 주기면 24)
	collect_start_dt date NOT NULL, -- 데이터 수집 기간-시작 (예: 2019-01 ~ 2024-12 이면 2019-01)
	collect_end_dt date NOT NULL, -- 데이터 수집 기간-종료 (예: 2019-01 ~ 2024-12 이면 2024-12)
	src_stat_title varchar(400) NOT NULL, -- 원데이터 통계표명
	src_update_dt date NULL, --  자료갱신일 (예:2024-07-19)
	src_ref_dt date NULL, -- 참조일자
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_src_data_info PRIMARY KEY (src_data_id)
);
CREATE UNIQUE INDEX uidx_st_src_data_info_title_collect ON public.stats_src_data_info USING btree (stat_title, collect_cycle, collect_start_dt, collect_end_dt );
CREATE INDEX idx_st_src_data_info_org_ext ON public.stats_src_data_info USING btree (src_org, ext_sys );
COMMENT ON TABLE public.stats_src_data_info IS '통계성 데이터 수집  소스 데이터 정보';

-- Column comments

COMMENT ON COLUMN public.stats_src_data_info.src_data_id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_src_data_info.ext_api_id IS '연동 시스템 정보 ID, sys_ext_api_info.ext_api_id';
COMMENT ON COLUMN public.stats_src_data_info.ext_sys IS '데이터 수집한 외부 시스템 코드, "ext_sys_code" comm code 참조. ext_api_id.ext_sys_code 코드와 동일';
COMMENT ON COLUMN public.stats_src_data_info.stat_title IS '데이터명';
COMMENT ON COLUMN public.stats_src_data_info.src_org IS '작성기관 코드 , "stats_data_src_org" comm code 참조';
COMMENT ON COLUMN public.stats_src_data_info.src_title IS '조사명';
COMMENT ON COLUMN public.stats_src_data_info.src_pub_dt IS '작성시점';
COMMENT ON COLUMN public.stats_src_data_info.collect_cycle IS '데이터 수집 주기 (개월 단위, 연간이면 12, 2년 주기면 24)';
COMMENT ON COLUMN public.stats_src_data_info.collect_start_dt IS '데이터 수집 기간-시작 (예: 2019-01 ~ 2024-12 이면 2019-01)';
COMMENT ON COLUMN public.stats_src_data_info.collect_end_dt IS '데이터 수집 기간-종료 (예: 2019-01 ~ 2024-12 이면 2024-12)';
COMMENT ON COLUMN public.stats_src_data_info.src_stat_title IS '원데이터 통계표명';
COMMENT ON COLUMN public.stats_src_data_info.src_update_dt IS '자료갱신일 (예:2024-07-19)';
COMMENT ON COLUMN public.stats_src_data_info.src_ref_dt IS '테이터 참조일자';
COMMENT ON COLUMN public.stats_src_data_info.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_src_data_info.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_src_data_info.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_src_data_info.updated_by IS '데이터 수정자';




-- #### 주거 자립 현황 ####

-- # public.stats_dis_reg_natl_by_new definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_reg_natl_by_new;

CREATE TABLE public.stats_dis_reg_natl_by_new (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	target_age int2 NOT NULL, -- 연령 (예: 0세, 1세등)
	gender bpchar(1) NOT NULL, -- 성별, "gender" comm code (예: 남성,여성)
	dis_type varchar(8) NOT NULL, -- 15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)
	dis_severity varchar(8) NOT NULL, -- 장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)
	reg_cnt int4 NOT NULL, -- 등록 인원 수
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_disability_reg_natl_by_new PRIMARY KEY (id)
);
CREATE INDEX idx_st_disability_reg_natl_by_new_year ON public.stats_dis_reg_natl_by_new USING btree (stat_year);
CREATE INDEX idx_st_disability_reg_natl_by_new_age_gen_dis ON public.stats_dis_reg_natl_by_new USING btree (target_age, gender, dis_type, dis_severity);
COMMENT ON TABLE public.stats_dis_reg_natl_by_new IS '기초-주거 자립 현황- 전국 장애인 신규등록 장애인 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.target_age IS '연령 (예: 0세, 1세등)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.gender IS '성별, "gender" comm code (예: 남성,여성)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.dis_type IS '15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.dis_severity IS '장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.reg_cnt IS '등록 인원 수';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_new.updated_by IS '데이터 수정자';


-- public.stats_dis_reg_natl_by_new foreign keys

ALTER TABLE public.stats_dis_reg_natl_by_new ADD CONSTRAINT fk_src_d_info_to_st_dis_reg_natl_by_new FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_reg_sido_by_age_type_sev_gen definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_reg_sido_by_age_type_sev_gender;

CREATE TABLE public.stats_dis_reg_sido_by_age_type_sev_gen (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	sido_hcode varchar(10) NOT NULL, -- 시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고 
	gender bpchar(1) NOT NULL, -- 성별, "gender" comm code (예: 남성,여성)
	dis_type varchar(8) NOT NULL, -- 15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)
	dis_severity varchar(8) NOT NULL, -- 장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)
	reg_cnt int4 NOT NULL, -- 등록 인원 수
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_reg_by_sido_age_ty_sev_gen PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_reg_sido_by_age_ty_sev_gen_year ON public.stats_dis_reg_sido_by_age_type_sev_gen USING btree (stat_year);
CREATE INDEX idx_st_dis_reg_sido_by_age_ty_sev_gen_sido_gen_dis ON public.stats_dis_reg_sido_by_age_type_sev_gen USING btree (sido_hcode, gender, dis_type, dis_severity);
COMMENT ON TABLE public.stats_dis_reg_sido_by_age_type_sev_gen IS '기초-주거 자립 현황-시도별,장애유형별,장애정도별,성별 등록장애인수';

-- Column comments

COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.sido_hcode IS '시도 코드 (행정동 코드 기준), sys_code_haeng_beop_dong TB 참고 ';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.gender IS '성별, "gender" comm code (예: 남성,여성)';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.dis_type IS '15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.dis_severity IS '장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.reg_cnt IS '등록 인원 수';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_dis_reg_sido_by_age_type_sev_gen.updated_by IS '데이터 수정자';


-- public.stats_dis_reg_sido_by_age_type_sev_gender foreign keys

ALTER TABLE public.stats_dis_reg_sido_by_age_type_sev_gen ADD CONSTRAINT fk_src_d_info_to_st_dis_reg_sido_by_age_ty_sev_gen FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_reg_natl_by_age_type_sev_gen definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_reg_natl_by_age_type_sev_gen;

CREATE TABLE public.stats_dis_reg_natl_by_age_type_sev_gen (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	age_range varchar(10) NOT NULL, -- 연령대,  "age_range" Common gode (예: 0세~4세, 05~09세등)
	target_age int2 NOT NULL, -- 연령 (예: 0세, 1세등)
	gender bpchar(1) NOT NULL, -- 성별, "gender" comm code (예: 남성,여성)
	dis_type varchar(8) NOT NULL, -- 15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)
	dis_severity varchar(8) NOT NULL, -- 장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)
	reg_cnt int4 NOT NULL, -- 등록 인원 수
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NULL, -- 데이터  등록자
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_reg_natl_by_age_type_sev_gen PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_reg_natl_by_age_t_sev_gen_gen_dis ON public.stats_dis_reg_natl_by_age_type_sev_gen USING btree (gender, dis_type, dis_severity);
CREATE INDEX idx_st_dis_reg_natl_by_age_t_sev_gen_year_age ON public.stats_dis_reg_natl_by_age_type_sev_gen USING btree (stat_year, age_range, target_age);
COMMENT ON TABLE public.stats_dis_reg_natl_by_age_type_sev_gen IS '기초-주거 자립 현황-전국 연령별,장애등급별,성별 등록장애인수';

-- Column comments

COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.age_range IS '연령대,  "age_range" Common gode (예: 0세~4세, 05~09세등)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.target_age IS '연령 (예: 0세, 1세등)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.gender IS '성별, "gender" comm code (예: 남성,여성)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.dis_type IS '15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.dis_severity IS '장애정도 , "disability_severity"  comm code (예: 심한 장애, 경증 장애)';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.reg_cnt IS '등록 인원 수';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.created_by IS '데이터  등록자';
COMMENT ON COLUMN public.stats_dis_reg_natl_by_age_type_sev_gen.updated_by IS '데이터 수정자';


-- public.stats_dis_reg_natl_by_age_type_sev_gender foreign keys

ALTER TABLE public.stats_dis_reg_natl_by_age_type_sev_gen ADD CONSTRAINT fk_src_d_info_to_st_dis_reg_natl_by_age_ty_sev_gen FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_life_supp_need_lvl definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_life_supp_need_lvl;

CREATE TABLE public.stats_dis_life_supp_need_lvl (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	dis_type varchar(8) NOT NULL, -- 15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)
	lvl_sf_fu_pct numeric(5, 2) NOT NULL, -- 혼자서 스스로 가능 (%) 
    lvl_sf_mo_pct numeric(5, 2) NOT NULL, -- 대부분 혼자서 가능 (%) 
    lvl_nd_so_pct numeric(5, 2) NOT NULL, -- 일부 지원 필요 (%)
    lvl_nd_mo_pct numeric(5, 2) NOT NULL, -- 대부분 지원 필요 (%)
    lvl_nd_fu_pct numeric(5, 2) NOT NULL, -- 거의 지원 필요 (%)

	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_life_supp_need_lvl PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_life_supp_need_lvl_year_type ON public.stats_dis_life_supp_need_lvl USING btree (stat_year, dis_type);
COMMENT ON TABLE public.stats_dis_life_supp_need_lvl IS '기초-주거 자립 현황-일상생활 필요 지원 정도';

-- Column comments

COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.stat_year IS '연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.dis_type IS '15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.lvl_sf_fu_pct IS '혼자서 스스로 가능 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.lvl_sf_mo_pct IS '대부분 혼자서 가능 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.lvl_nd_so_pct IS '일부 지원 필요 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.lvl_nd_mo_pct IS '대부분 지원 필요 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.lvl_nd_fu_pct IS '거의 지원 필요 (%)';

COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_life_supp_need_lvl.updated_by IS '데이터 수정자';


-- public.stats_dis_life_supp_need_lvl foreign keys

ALTER TABLE public.stats_dis_life_supp_need_lvl ADD CONSTRAINT fk_st_dis_life_supp_need_lvl FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_life_maincarer definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_life_maincarer;

CREATE TABLE public.stats_dis_life_maincarer (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	
	dis_type varchar(8) NOT NULL, -- 15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)
	spouse_pct numeric(5, 2) NOT NULL, -- 배우자 비율 (%)
	parent_pct numeric(5, 2) NOT NULL, -- 부모 비율 (%)
	child_pct numeric(5, 2) NOT NULL, -- 자녀(며느리, 사위 포함) 비율 (%)
	sibling_pct numeric(5, 2) NOT NULL, -- 형제, 자매 비율 (%)
	grandpar_pct numeric(5, 2) NOT NULL, -- 조부모 비율 (%)
	grandchi_pct numeric(5, 2) NOT NULL, -- 손자녀 비율 (%)
	othfamily_pct numeric(5, 2) NOT NULL, -- 기타 가족 비율 (%)
	relative_pct numeric(5, 2) NOT NULL, -- 친척 비율 (%)
	friend_pct numeric(5, 2) NOT NULL, -- 친구 비율 (%)
	neighbor_pct numeric(5, 2) NOT NULL, -- 이웃 비율 (%)
	actcarer_pct  numeric(5, 2) NOT NULL, -- 활동보조인 비율 (%)
	homeaid_pct numeric(5, 2) NOT NULL, -- 가정봉사원 비율 (%)
	caregiver_pct numeric(5, 2) NOT NULL, -- 간병인 비율 (%)
	careworker_pct numeric(5, 2) NOT NULL, -- 요양보호사 비율 (%)
	other_pct numeric(5, 2) NOT NULL, -- 기타 비율 (%)
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_life_maincarer PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_life_maincarer_year_type ON public.stats_dis_life_maincarer USING btree (stat_year, dis_type);
COMMENT ON TABLE public.stats_dis_life_maincarer IS '기초-주거 자립 현황-주로 지원해주는 사람의 유형';

-- Column comments

COMMENT ON COLUMN public.stats_dis_life_maincarer.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_life_maincarer.stat_year IS '연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_life_maincarer.dis_type IS '15종 장애 유형, "disability_type" comm code (예: 지체, 시각, 청각, 언어, 지적 등)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.spouse_pct IS '배우자 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.parent_pct IS '부모 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.child_pct IS '자녀(며느리, 사위 포함) 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.sibling_pct IS '형제, 자매 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.grandpar_pct IS '조부모 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.grandchi_pct IS '손자녀 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.othfamily_pct IS '기타 가족 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.relative_pct IS '친척 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.friend_pct IS '친구 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.neighbor_pct IS '이웃 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.actcarer_pct  IS '활동보조인 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.homeaid_pct IS '가정봉사원 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.caregiver_pct IS '간병인 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.careworker_pct IS '요양보호사 비율 (%)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.other_pct IS '기타 비율 (%)';

COMMENT ON COLUMN public.stats_dis_life_maincarer.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_life_maincarer.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_life_maincarer.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_life_maincarer.updated_by IS '데이터 수정자';


-- public.stats_dis_life_maincarer foreign keys

ALTER TABLE public.stats_dis_life_maincarer ADD CONSTRAINT fk_st_dis_life_maincarer FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_life_1stcarer definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_life_1stcarer;

CREATE TABLE public.stats_dis_life_1stcarer (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	
	care_cat1 varchar(16) NOT NULL, -- 일상생활 지원 카테고리1, "life_care_stat_cat" comm code (예: 성별, 장애유형, 장애정도)
	care_cat2 varchar(12) NOT NULL, -- 일상생활 지원 카테고리2, "life_care_stat_cat" 따른 comm code (예: gender, life_care_dis_type, life_care_dis_sev)
	estm_cnt int4 NOT NULL, -- 추정수 (명)
	spouse_pct numeric(5, 2) NOT NULL, -- 배우자 (%)
	parent_pct numeric(5, 2) NOT NULL, -- 부모 (%)
	child_pct numeric(5, 2) NOT NULL, -- 자녀 (%)
	sibling_pct numeric(5, 2) NOT NULL, -- 형제, 자매 (%)
	relative_pct numeric(5, 2) NOT NULL, -- 친인척 (%)
	frd_nbr_pct numeric(5, 2) NOT NULL, -- 친구 및 이웃 (%)
	paid_care_pct  numeric(5, 2) NOT NULL, -- 유료 간병인/가정봉사원 (%)
	actcarer_pct  numeric(5, 2) NOT NULL, -- 활동지원사 (%)
	unpaid_care_pct   numeric(5, 2) NOT NULL, -- 무료 간병인/가정봉사원 (%)
	careworker_pct numeric(5, 2) NOT NULL, -- 요양보호사 (%)
	religious_pct numeric(5, 2) NOT NULL, -- '종교단체 관계자 (%)
	socworker_pct  numeric(5, 2) NOT NULL, -- '사회 복지사 (%)
	nosupport_pct numeric(5, 2) NOT NULL, -- 없음 (%)
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_life_1stcarer PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_life_1stcarer_year_care ON public.stats_dis_life_1stcarer USING btree (stat_year, care_cat1, care_cat2);
COMMENT ON TABLE public.stats_dis_life_1stcarer IS '기초-주거 자립 현황-일상생활 도와주는 사람(1순위)';

-- Column comments

COMMENT ON COLUMN public.stats_dis_life_1stcarer.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.stat_year IS '연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_life_1stcarer.care_cat1 IS '일상생활 지원 카테고리1, "life_care_stat_cat" comm code (예: 성별, 장애유형, 장애정도)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.care_cat2 IS '일상생활 지원 카테고리2, "life_care_stat_cat" 따른 comm code (예: gender, life_care_dis_type, life_care_dis_sev)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.estm_cnt IS '추정수 (명)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.spouse_pct IS '배우자 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.parent_pct IS '부모 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.child_pct IS '자녀 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.sibling_pct IS '형제 자매 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.relative_pct IS '친인척 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.frd_nbr_pct IS '친구 및 이웃 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.paid_care_pct  IS '유료 간병인/가정봉사원 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.actcarer_pct  IS '활동지원사 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.unpaid_care_pct  IS '무료 간병인/가정봉사원 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.careworker_pct IS '요양보호사 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.religious_pct  IS '종교단체 관계자 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.socworker_pct   IS '사회 복지사 (%)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.nosupport_pct IS '없음 (%)';

COMMENT ON COLUMN public.stats_dis_life_1stcarer.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_life_1stcarer.updated_by IS '데이터 수정자';


-- public.stats_dis_life_1stcarer foreign keys

ALTER TABLE public.stats_dis_life_1stcarer ADD CONSTRAINT fk_st_dis_life_1stcarer FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_life_supp_field definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_life_supp_field;

CREATE TABLE public.stats_dis_life_supp_field (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	
	supp_field varchar(12) NOT NULL, -- 장애인 생활 도움 분야 , "life_care_supp_field" comm code (예: 전반적 일상생활,세면 및 개인위생관리, .. )
	estm_cnt int4 NOT NULL, -- 추정수 (명)
	no_supp_pct  numeric(5, 2) NOT NULL, -- 전혀 도움받지 않음 (%)
	little_supp_pct numeric(5, 2) NOT NULL, -- 거의 도움받지 않는 편임 (%)
	mod_supp_pct numeric(5, 2) NOT NULL, -- 도움받고 있는 편임 (%)
	full_supp_pct numeric(5, 2) NOT NULL, -- 전적으로 도움받음 (%)
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_life_supp_field PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_life_supp_field_year_field ON public.stats_dis_life_supp_field USING btree (stat_year, supp_field);
COMMENT ON TABLE public.stats_dis_life_supp_field IS '기초-주거 자립 현황-도움받는 분야';

-- Column comments

COMMENT ON COLUMN public.stats_dis_life_supp_field.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_life_supp_field.stat_year IS '연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_life_supp_field.supp_field IS '장애인 생활 도움 분야 , "life_care_supp_field" comm code (예: 전반적 일상생활,세면 및 개인위생관리, .. )';
COMMENT ON COLUMN public.stats_dis_life_supp_field.estm_cnt IS '추정수 (명)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.no_supp_pct IS '전혀 도움받지 않음 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.little_supp_pct IS '거의 도움받지 않는 편임 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.mod_supp_pct IS '도움받고 있는 편임 (%)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.full_supp_pct IS '전적으로 도움받음 (%)';

COMMENT ON COLUMN public.stats_dis_life_supp_field.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_life_supp_field.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_life_supp_field.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_life_supp_field.updated_by IS '데이터 수정자';


-- public.stats_dis_life_supp_field foreign keys

ALTER TABLE public.stats_dis_life_supp_field ADD CONSTRAINT fk_st_dis_life_supp_field FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);




-- #### 건강 관리 현황 ####

-- # public.stats_dis_hlth_medical_usage definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_hlth_medical_usage;

CREATE TABLE public.stats_dis_hlth_medical_usage (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
	
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_hlth_medi_usage PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_hlth_medi_usageyear_c1t3 ON public.stats_dis_hlth_medical_usage USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_hlth_medical_usage IS '기초-건강 관리 현황-장애인 의료이용 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_hlth_medical_usage.updated_by IS '데이터 수정자';


-- public.stats_dis_hlth_medical_usage foreign keys

ALTER TABLE public.stats_dis_hlth_medical_usage ADD CONSTRAINT fk_st_dis_hlth_medi_usage FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_hlth_disease_cost_sub definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_hlth_disease_cost_sub;

CREATE TABLE public.stats_dis_hlth_disease_cost_sub (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
	
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_hlth_dcost_sub PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_hlth_dcost_subyear_c1t3 ON public.stats_dis_hlth_disease_cost_sub USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_hlth_disease_cost_sub IS '기초-건강 관리 현황-장애인 장애유형별 다빈도질환별 진료비현황: 소분류 (maj(대)/mid(중)/sub(소))';

-- Column comments

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_hlth_disease_cost_sub.updated_by IS '데이터 수정자';


-- public.stats_dis_hlth_disease_cost_sub foreign keys

ALTER TABLE public.stats_dis_hlth_disease_cost_sub ADD CONSTRAINT fk_st_dis_hlth_dcost_sub FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_hlth_sport_exec_type definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_hlth_sport_exec_type;

CREATE TABLE public.stats_dis_hlth_sport_exec_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
	
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_hlth_sport_exec_type PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_hlth_sport_exec_type_year_c1t3 ON public.stats_dis_hlth_sport_exec_type USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_hlth_sport_exec_type IS '기초-건강 관리 현황-장애인 생활체육 실행 유형';

-- Column comments

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_hlth_sport_exec_type.updated_by IS '데이터 수정자';


-- public.stats_dis_hlth_sport_exec_type foreign keys

ALTER TABLE public.stats_dis_hlth_sport_exec_type ADD CONSTRAINT fk_st_dis_hlth_sport_exec_type FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_hlth_exrc_best_aid definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_hlth_exrc_best_aid;

CREATE TABLE public.stats_dis_hlth_exrc_best_aid (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
	
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_hlth_exrc_best_aid PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_hlth_exrc_best_aid_year_c1t3 ON public.stats_dis_hlth_exrc_best_aid USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_hlth_exrc_best_aid IS '기초-건강 관리 현황-운동 시 가장 도움이 되는 지원 사항';

-- Column comments

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_hlth_exrc_best_aid.updated_by IS '데이터 수정자';


-- public.stats_dis_hlth_exrc_best_aid foreign keys

ALTER TABLE public.stats_dis_hlth_exrc_best_aid ADD CONSTRAINT fk_st_dis_hlth_exrc_best_aid FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);




-- #### 보조기기 사용 현황 ####

-- # public.stats_dis_aid_device_usage definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_aid_device_usage;

CREATE TABLE public.stats_dis_aid_device_usage (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
	
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_aid_device_usage PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_aid_device_usage_year_c1t3 ON public.stats_dis_aid_device_usage USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_aid_device_usage IS '기초-보조기기 사용 현황-장애인보조기기 사용여부';

-- Column comments

COMMENT ON COLUMN public.stats_dis_aid_device_usage.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_aid_device_usage.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_aid_device_usage.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_aid_device_usage.updated_by IS '데이터 수정자';


-- public.stats_dis_aid_device_usage foreign keys

ALTER TABLE public.stats_dis_aid_device_usage ADD CONSTRAINT fk_st_dis_aid_device_usage FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_aid_device_need definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_aid_device_need;

CREATE TABLE public.stats_dis_aid_device_need (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_aid_device_need PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_aid_device_need_year_c1t3 ON public.stats_dis_aid_device_need USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_aid_device_need IS '기초-보조기기 사용 현황-장애인보조기기 필요여부';

-- Column comments

COMMENT ON COLUMN public.stats_dis_aid_device_need.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_aid_device_need.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_aid_device_need.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_aid_device_need.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_aid_device_need.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_aid_device_need.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_aid_device_need.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_aid_device_need.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_aid_device_need.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_aid_device_need.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_aid_device_need.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_aid_device_need.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_aid_device_need.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_aid_device_need.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_aid_device_need.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_aid_device_need.updated_by IS '데이터 수정자';


-- public.stats_dis_aid_device_need foreign keys

ALTER TABLE public.stats_dis_aid_device_need ADD CONSTRAINT fk_st_dis_aid_device_need FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);





-- #### 진로 교육 현황 ####


-- # public.stats_dis_edu_voca_exec definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_edu_voca_exec;

CREATE TABLE public.stats_dis_edu_voca_exec (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_edu_voca_exec PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_edu_voca_exec_year_c1t3 ON public.stats_dis_edu_voca_exec USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_edu_voca_exec IS '기초-진로 교육 현황-장애인 진로 및 직업교육 실시 여부';

-- Column comments

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_edu_voca_exec.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec.updated_by IS '데이터 수정자';


-- public.stats_dis_edu_voca_exec foreign keys

ALTER TABLE public.stats_dis_edu_voca_exec ADD CONSTRAINT fk_st_dis_edu_voca_exec FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_edu_voca_exec_way definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_edu_voca_exec_way;

CREATE TABLE public.stats_dis_edu_voca_exec_way (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_edu_voca_exec_way PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_edu_voca_exec_way_year_c1t3 ON public.stats_dis_edu_voca_exec_way USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_edu_voca_exec_way IS '기초-진로 교육 현황-장애인 진로 및 직업교육 운영 방법';

-- Column comments

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_edu_voca_exec_way.updated_by IS '데이터 수정자';


-- public.stats_dis_edu_voca_exec_way foreign keys

ALTER TABLE public.stats_dis_edu_voca_exec_way ADD CONSTRAINT fk_st_dis_edu_voca_exec_way FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);





-- #### 고용 현황 ####


-- # public.stats_dis_emp_natl definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl;

CREATE TABLE public.stats_dis_emp_natl (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	cat_main varchar(20) NOT NULL, -- 카테고리 메인, "dis_emp_category" comm code  ( 예 :고용 의무/비의무기업 규모별, 부담금 납부, 산업별, 성별)
	cat_sub varchar(20) NOT NULL, -- 카테고리 서브, dis_emp_category 따른 세부( non_mand_emp_size, mand_emp_size, industry_type 등 )  ( 예 :[1~4명, 5~49명], [50~299명, 300~999명, 1000이사], [제조업, 서비스업, 기타], [남,여])
	emp_reglr_cnt int4 NOT NULL, -- 상시근로자 수
	emp_reglr_pct numeric(5, 2) NOT NULL, -- 상시근로자 비율(%)
	emp_dis_reglr_cnt int4 NOT NULL, -- 장애인 상시근로자 수
	emp_dis_reglr_pct numeric(5, 2) NOT NULL, -- 장애인 상시근로자 비율 (%)
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_year_cat ON public.stats_dis_emp_natl USING btree (stat_year, cat_main, cat_sub);
COMMENT ON TABLE public.stats_dis_emp_natl IS '기초-고용 현황-장애인 근로자 고용현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl.cat_main IS '카테고리 메인, "dis_emp_category" comm code  ( 예 :고용 의무/비의무기업 규모별, 부담금 납부, 산업별, 성별)';
COMMENT ON COLUMN public.stats_dis_emp_natl.cat_sub IS '카테고리 서브, dis_emp_category 따른 세부( non_mand_emp_size, mand_emp_size, emp_dis_indust_type 등 )  ( 예 :[1~4명, 5~49명], [50~299명, 300~999명, 1000이사], [제조업, 서비스업, 기타], [남,여])';
COMMENT ON COLUMN public.stats_dis_emp_natl.emp_reglr_cnt IS '상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl.emp_reglr_pct IS '상시근로자 비율(%)';
COMMENT ON COLUMN public.stats_dis_emp_natl.emp_dis_reglr_cnt IS '장애인 상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl.emp_dis_reglr_pct IS '장애인 상시근로자 비율 (%)';
COMMENT ON COLUMN public.stats_dis_emp_natl.emp_dis_pct IS '장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율';
COMMENT ON COLUMN public.stats_dis_emp_natl.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl foreign keys

ALTER TABLE public.stats_dis_emp_natl ADD CONSTRAINT fk_st_dis_emp_natl FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_emp_natl_public definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl_public;

CREATE TABLE public.stats_dis_emp_natl_public (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	pub_agcy_type varchar(12) NOT NULL, -- 공공기관, "public_agency_type" comm code  ( 예 :공기업, 준정부기관, 기타공공기관, 지방공기업,출자출연기관)
	agcy_cnt int4 NOT NULL, -- 사업체 수
	emp_reglr_cnt int4 NOT NULL, -- 상시근로자 수
	emp_dis_reglr_cnt int4 NOT NULL, -- 장애인 상시근로자 수
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl_pub PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_pub_year_agcy ON public.stats_dis_emp_natl_public USING btree (stat_year, pub_agcy_type);
COMMENT ON TABLE public.stats_dis_emp_natl_public IS '기초-고용 현황-공공기관 장애인고용 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl_public.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.pub_agcy_type IS '공공기관, "public_agency_type" comm code  ( 예:공기업, 준정부기관, 기타공공기관, 지방공기업,출자출연기관 )';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.agcy_cnt IS '사업체 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.emp_reglr_cnt IS '상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.emp_dis_reglr_cnt IS '장애인 상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.emp_dis_pct IS '장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl_public.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl_public foreign keys

ALTER TABLE public.stats_dis_emp_natl_public ADD CONSTRAINT fk_st_dis_emp_natl_pub FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_emp_natl_private definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl_private;

CREATE TABLE public.stats_dis_emp_natl_private (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	comp_sz_type varchar(20) NOT NULL, -- 민간업체 고용규모 타입, "emp_private_comp_sz_type" comm code  ( 예:100 이하, 100~299인, 300~499인, 500~999인, 1000인 이상)
	comp_cnt int4 NOT NULL, -- 사업체 수
	emp_reglr_cnt int4 NOT NULL, -- 상시근로자 수
	emp_dis_reglr_cnt int4 NOT NULL, -- 장애인 상시근로자 수
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl_priv PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_priv_year_comp ON public.stats_dis_emp_natl_private USING btree (stat_year, comp_sz_type);
COMMENT ON TABLE public.stats_dis_emp_natl_private IS '기초-고용 현황-민간기업 장애인고용 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl_private.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.comp_sz_type IS '민간업체 고용규모 타입, "emp_private_comp_sz_type" comm code  ( 예 :100 이하, 100~299인, 300~499인, 500~999인, 1000인 이상)';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.comp_cnt IS '사업체 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.emp_reglr_cnt IS '상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.emp_dis_reglr_cnt IS '장애인 상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.emp_dis_pct IS '장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl_private.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl_private foreign keys

ALTER TABLE public.stats_dis_emp_natl_private ADD CONSTRAINT fk_st_dis_emp_natl_priv FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);

-- # public.stats_dis_emp_natl_gov_org definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl_gov_org;

CREATE TABLE public.stats_dis_emp_natl_gov_org (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	gov_emp_type varchar(12) NOT NULL, -- 고용현황별 , "gov_emp_type" comm code (예:공무원,근로자)
	gov_org_type varchar(20) NOT NULL, -- 정부부문별 타입, "gov_organization_type" comm code  ( 예 :중앙행정기관, 헌법기관, 지방자치단체, 교육청)
	comp_cnt int4 NOT NULL, -- 사업체 수
	emp_reglr_cnt int4 NOT NULL, -- 상시근로자 수
	emp_dis_reglr_cnt int4 NOT NULL, -- 장애인 상시근로자 수
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl_gov_org PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_gov_org_year_gov ON public.stats_dis_emp_natl_gov_org USING btree (stat_year, gov_emp_type, gov_org_type);
COMMENT ON TABLE public.stats_dis_emp_natl_gov_org IS '기초-고용 현황-정부부문 장애인고용 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.gov_emp_type is '고용현황별 , "gov_dis_emp_type" comm code (예:공무원,근로자)';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.gov_org_type IS '정부부문별 타입, "gov_organization_type" comm code  ( 예 :중앙행정기관, 헌법기관, 지방자치단체, 교육청)';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.comp_cnt IS '사업체 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.emp_reglr_cnt IS '상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.emp_dis_reglr_cnt IS '장애인 상시근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.emp_dis_pct IS '장애인 고용률 (%) : 전체 상시근로자 중 장애인 고용비율';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl_gov_org.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl_gov_org foreign keys

ALTER TABLE public.stats_dis_emp_natl_gov_org ADD CONSTRAINT fk_st_dis_emp_natl_gov_org FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_emp_natl_dis_type_sev definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl_dis_type_sev;

CREATE TABLE public.stats_dis_emp_natl_dis_type_sev (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	
	emp_dis_ty_sev_cat varchar(10) DEFAULT 'DIS_TYPE' NOT NULL, -- 고용 장애유형및 정도 분류 카테고리 "emp_dis_type_sev_cat" comm code  ( 예:장애유형별)
	emp_dis_cls varchar(20) NOT NULL, -- 고용통계 장애 분류 "emp_disability_class" comm code  ( 예:신체외부장애, 감각장애, 정신적장애, 신체내부장애, 국가유공자)
	emp_dis_cls_sub varchar(12) NOT NULL, -- 고용통계 장애 서브 분류, "emp_disability_class" comm code 따른 세브 코드  ( 예:emp_dis_ext_bd_type, emp_dis_sens_type, emp_dis_mental_type)
	
	emp_dis_cnt int4 NOT NULL, -- 장애인 근로자 수
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%)
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl_dis_ty_sev PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_dis_ty_sev_year_cat_cls ON public.stats_dis_emp_natl_dis_type_sev USING btree (stat_year, emp_dis_ty_sev_cat, emp_dis_cls, emp_dis_cls_sub);
COMMENT ON TABLE public.stats_dis_emp_natl_dis_type_sev IS '기초-고용 현황-장애유형 및 장애정도별 장애인 근로자 고용현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.emp_dis_ty_sev_cat IS '고용 장애유형및 정도 분류 카테고리 "emp_dis_type_sev_cat" comm code  ( 예:장애유형별)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.emp_dis_cls IS '고용통계 장애 분류 "emp_disability_class" comm code  ( 예:신체외부장애, 감각장애, 정신적장애, 신체내부장애, 국가유공자)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.emp_dis_cls_sub IS '고용통계 장애 서브 분류, "emp_disability_class" comm code 따른 세브 코드  ( 예:emp_dis_ext_bd_type, emp_dis_sens_type, emp_dis_mental_type)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.emp_dis_cnt IS '장애인 근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.emp_dis_pct IS '장애인 고용률 (%)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_sev.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl_dis_type_sev foreign keys

ALTER TABLE public.stats_dis_emp_natl_dis_type_sev ADD CONSTRAINT fk_st_dis_emp_natl_dis_ty_sev FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);


-- # public.stats_dis_emp_natl_dis_type_indust definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_emp_natl_dis_type_indust;

CREATE TABLE public.stats_dis_emp_natl_dis_type_indust (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	emp_dis_cls varchar(20) NOT NULL, -- 고용통계 장애 분류 "emp_disability_class" comm code  ( 예:신체외부장애, 감각장애, 정신적장애, 신체내부장애, 국가유공자)
	emp_dis_cls_sub varchar(12) NOT NULL, -- 고용통계 장애 서브 분류, "emp_disability_class" comm code 따른 세브 코드  ( 예:emp_dis_ext_bd_type, emp_dis_sens_type, emp_dis_mental_type)
    emp_ind_type varchar(12) NOT NULL, -- 고용 산업 분류 "emp_dis_industry_type" comm code  ( 예:제조업, 서비스업1, 서비스업2, 기타)
	stat_year int2 NOT NULL, -- 연도 (예: 2024)
	emp_dis_cnt int4 NOT NULL, -- 장애인 근로자 수
	emp_dis_pct numeric(5, 2) NOT NULL, -- 장애인 고용률 (%)
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	CONSTRAINT pkey_st_dis_emp_natl_dis_ty_ind PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_emp_natl_dis_ty_ind_year_cls_ind ON public.stats_dis_emp_natl_dis_type_indust USING btree (stat_year, emp_dis_cls, emp_dis_cls_sub, emp_ind_type);
COMMENT ON TABLE public.stats_dis_emp_natl_dis_type_indust IS '기초-고용 현황-장애유형 및 산업별 장애인 근로자 고용현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.emp_dis_cls IS '고용통계 장애 분류 "emp_disability_class" comm code  ( 예:신체외부장애, 감각장애, 정신적장애, 신체내부장애, 국가유공자)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.emp_dis_cls_sub IS '고용통계 장애 서브 분류, "emp_disability_class" comm code 따른 세브 코드  ( 예:emp_dis_ext_bd_type, emp_dis_sens_type, emp_dis_mental_type)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.emp_ind_type IS '고용 산업 분류 "emp_dis_industry_type" comm code  ( 예:제조업, 서비스업1, 서비스업2, 기타)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.stat_year IS '연도 (예: 2024)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.emp_dis_cnt IS '장애인 근로자 수';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.emp_dis_pct IS '장애인 고용률 (%)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_emp_natl_dis_type_indust.updated_by IS '데이터 수정자';


-- public.stats_dis_emp_natl_dis_type_indust foreign keys

ALTER TABLE public.stats_dis_emp_natl_dis_type_indust ADD CONSTRAINT fk_st_dis_emp_natl_dis_ty_ind FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);





-- #### 사회망 현황 ####


-- # public.stats_dis_soc_partic_freq definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_soc_partic_freq;

CREATE TABLE public.stats_dis_soc_partic_freq (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_soc_partic_freq PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_soc_partic_freq_year_c1t3 ON public.stats_dis_soc_partic_freq USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_soc_partic_freq IS '기초-사회망 현황-장애인의 사회 참여';

-- Column comments

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_soc_partic_freq.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_soc_partic_freq.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_soc_partic_freq.updated_by IS '데이터 수정자';


-- public.stats_dis_soc_partic_freq foreign keys

ALTER TABLE public.stats_dis_soc_partic_freq ADD CONSTRAINT fk_st_dis_soc_partic_freq FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);



-- # public.stats_dis_soc_contact_cntfreq definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_soc_contact_cntfreq;

CREATE TABLE public.stats_dis_soc_contact_cntfreq (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_soc_contact_cntfreq PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_soc_contact_cntfreq_year_c1t3 ON public.stats_dis_soc_contact_cntfreq USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_soc_contact_cntfreq IS '기초-사회망 현황-가까이 지내는 친구, 이웃, 지인 수 및 만남 빈도';

-- Column comments

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_soc_contact_cntfreq.updated_by IS '데이터 수정자';


-- public.stats_dis_soc_contact_cntfreq foreign keys

ALTER TABLE public.stats_dis_soc_contact_cntfreq ADD CONSTRAINT fk_st_dis_soc_contact_cntfreq FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);






-- #### 편의 시설 제공 현황 ####


-- # public.stats_dis_fclty_welfare_usage definition

-- Drop table

-- DROP TABLE IF EXISTS public.stats_dis_fclty_welfare_usage;

CREATE TABLE public.stats_dis_fclty_welfare_usage (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- system id, 고유 식별자 (자동 증가)
	src_data_id int4 NOT NULL, -- 소스 데이터 정보 ID, stats_src_data_info.src_data_id
	
	prd_de int2 NOT NULL, -- 수록시점, 연도 (예: 2024)
	
	c1 VARCHAR(10) NOT NULL, c2 VARCHAR(10), c3 VARCHAR(10), -- 분류값 ID1 ~ 3, 값 > 3자일 일경우: 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류

    itm_id VARCHAR(10) NOT NULL,           -- 항목 ID
    
    unit_id VARCHAR(4),                   -- 단위ID
    unit_nm VARCHAR(10) NOT NULL,                 -- 단위명
    
    dt VARCHAR(100),                       -- 수치 값
	
    lst_chn_de date,                 -- 최종수정일
	
	
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 생성 시각
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 레코드 수정 시각
	created_by varchar(40) NOT NULL, -- 데이터  등록자 (BACH, MANUAL, user id)
	updated_by varchar(40) NULL, -- 데이터 수정자
	
	CONSTRAINT pkey_st_dis_fclty_welfare_usage PRIMARY KEY (id)
);
CREATE INDEX idx_st_dis_fclty_welfare_usage_year_c1t3 ON public.stats_dis_fclty_welfare_usage USING btree (prd_de, c1, c2, c3);
COMMENT ON TABLE public.stats_dis_fclty_welfare_usage IS '기초-편의 시설 제공 현황-사회복지시설 이용 현황';

-- Column comments

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.id IS 'system id, 고유 식별자 (자동 증가)';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.src_data_id IS '소스 데이터 정보 ID, stats_src_data_info.src_data_id';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.prd_de IS '수록시점, 연도 (예: 2024)';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.c1 IS '분류값 ID1, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.c2 IS '분류값 ID2, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.c3 IS '분류값 ID3, 값>3자이고 첫문자가 문자인 경우 앞3자리는  group id, 검색 후 group id nm으 로표시. c#_obj하위에 group임. c#_obj > c# group > c#, itm_id는 별도 분류';


COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.itm_id IS '항목 ID';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.unit_id IS '단위 ID';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.unit_nm IS '단위명';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.prd_de IS '수록시점';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.dt IS '수치 값';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.lst_chn_de IS '최종 수정일';

COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.updated_at IS '레코드 수정 시각';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.created_by IS '데이터  등록자 (BACH, MANUAL, user id)';
COMMENT ON COLUMN public.stats_dis_fclty_welfare_usage.updated_by IS '데이터 수정자';


-- public.stats_dis_fclty_welfare_usage foreign keys

ALTER TABLE public.stats_dis_fclty_welfare_usage ADD CONSTRAINT fk_st_dis_fclty_welfare_usage FOREIGN KEY (src_data_id) REFERENCES public.stats_src_data_info(src_data_id);
